ansible_become_pass: ENC[AES256_GCM,data:AcLqm9OY,iv:FQPyGzdyzeNvA/ESN+vNEFFWEM4LXY8wL8ihK05pLOc=,tag:96FxLpqA5GwlEKcHRbR8gw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlejcwcTVvQ3IxU0R3VVh2
            ZlFNbjhXYUNUREhrZGhMNGdFTWRzdVVJR0NjCmdUSnFGSUN3VHduQ3hoZnd1K3Bo
            VHdVekUrbERUUEJTYk9mQkF3VnVMRVUKLS0tIFVRZEJFRVBzSEJ1OUYrbXNrNHZS
            UEUxeFEzbzBVbEtmWVlsUVlxR01BeHcKnxiD/UO1B3Z+XF4Vh1FXx7eEyxtVMEO1
            C4HJAo02xTjuKvMmRxWQ9cvRF+f6Zr8F4CpumGb2phtaxhFnzVCWqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-25T19:31:43Z"
    mac: ENC[AES256_GCM,data:vVpoaNyZEKWZI9H6KX2KPUdPzJwN+BfHEqJuCSOwSQ27uzqGWCQHm7Krs1UWySBcLl7uDSoBLHJS6MCexNzgprWomuNU3Yxg9DvexqdgxL3qbqOuBFHLcNTlM3Mea1pogzhpaMitEQvCE9vYfNYMpruwerCWQafBfelzvNSwpR4=,iv:HamvFSb9aj9Z3k9u8X5c9W0Rvh/vFPkohXhP0AepS5Q=,tag:LMNNHvspkcAMpJGIVkQ5Xg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
