ansible_become_pass: ENC[AES256_GCM,data:QbeF+nFT,iv:2iKo+dW0B9L5i2em5ukv+85zpJZ+RysAUYFyhLC5Vyo=,tag:91oXzDYa9OkhIE4VkXZ4ng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVVdkNXVxNHR4TTh2Mkov
            YWZGMzl4K0ZrcEh6VzZHVXhSakd2Y1I5T1NVClR3TjIvd2xCYXRjcDRuaXFTcjNR
            NXY3UlU0Q2Y2WGQ4bEZyYmdVWFFMQ3cKLS0tIC9WclFWbXZUWENlWHdMNzRMQyt6
            NnNZYkd5bloyN0N4WHRnUFhkSThPZmcKZ4ir89qYxu5gZ3EiyhIW/u+rcKyrbPPe
            US9EgqVGkNRWwZtV344RJ0lrx995RHlDI5F9awUnr9J3KtfLS89q/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-29T13:10:15Z"
    mac: ENC[AES256_GCM,data:i1LsQ909+pPGl4Oj+gQmJZ0Z6qvFf2nCPAELi0DF96YuryeT9XUaAm/EJKnxATLTrgzToNohOqwLFKYQ26cVYXKAEpnkY4GPUYeIcUJxjSx0D7dYctlEZpjwpjlxikPHWwzQdu1ZotNMhpM9+4DoED8L9iRM1BaIRz5/Y7/V1Qc=,iv:OiElIkQMOd08alipaCWV8ZGEbHKatUETwNIrk/12Snk=,tag:fWdjktQtKTBROycxlmlzhw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
