ansible_become_pass: ENC[AES256_GCM,data:6JufClR/,iv:T6TVqQXnHeg3EMv7A9nIFFU82ho7hv25M50O6aGJMMY=,tag:17tS/L61a9CMp9KjVgCAlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIb1pQTXpsOVN4SGFRang1
            TWNGNCtCY29rNHFtM09USTRtWWNVOUhTQnhZClpYWnhLQTlnSXZvMllLUzgzNHNO
            SGEyY05XMFFhbnNJN21KVjQrWlIxRWsKLS0tIDQzOHJvUVcyTnRqdXRzWGpKOW5N
            RUNHMjdROHE0VXdSSVByR2VGRFBHYUkKAuw7kKLjc4NR37VHz5QemMVAdcNxNSCP
            4uiVuagYmE+0VTzxShm6wd8cJAcuCuSRJWwBpAOkA/Qc9/V87WH61w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-23T21:42:00Z"
    mac: ENC[AES256_GCM,data:XVC6nknJoC5Nq9aVzSsP2I2XUDos1Uv6+3A3N59EEA5lA1ArtVi30a54l453aADgKgZRWULyZCXdas2xPUZWg63LgKkXfVsfPTlcHf+tw38TElCdYia/gvJRYehDLYxAsO20mwhUITBYbjMm0owj1cqmBrAq0NLH74Xv3Q0SK5Q=,iv:jgr75vAjFGHb3z+3IkNoAhQNwhVWkwRtjMnWPtqAVho=,tag:aWEADoxi09MZ9dkG/cQWgQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
