ansible_become_pass: ENC[AES256_GCM,data:R9CZBmqN,iv:zNzvU/HzaHQ1xkElTXkrreD00WpOo7z4KrdTl+Mc5fE=,tag:alg0296Puq1u/vty3NBUaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqd25iZTU5YkFMejNBSjgz
            SDFhaGxQWnRwN3NWUnc2THlPZ1RxemoxMkVvClVwZmRnRHFKeUVNWXRodC85UEk5
            VVNFb3JsejRITlRnMXI3RDRJMFBUYUkKLS0tIEFEMEdXUnJLcmt5MWcraWdqUTBU
            STVHa2RwZ2ZRNWdRMmdhNXhhVFliQTQKW89IYvTFB62jYC6T4Un90wJLgjTEPN3I
            FsXngnCUALWXNNDDAbXlzICtyJmCAri7e1Pr7OogDgbJ0nbCefUKZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T17:30:18Z"
    mac: ENC[AES256_GCM,data:ElgV6DOL+Igj5fLMdNE9cQIWb+lNhzHRMZH9dM7Dz+mAnIL0HbnC7nK9cqICkymRZWKdXHJqnkzexXyCuSIIQupEmqewqPQnYhY701Upr215z8yiQxUnScRdKr3aw3pNU4lDOAEVgk5Y8tH0C/jMLEc1GNRdpsngoZCOoMBKJNk=,iv:VTfAC/BbB0tZCkJ9DRCAgH5+LCVRknIsxluDwJp1wFQ=,tag:3v8f6rCiUH89NdqvUA5EsQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
