ansible_become_pass: ENC[AES256_GCM,data:/89mQnyz,iv:jcu8caepEG8D5lJJ+gfxkBgpgKWDhg+BopebJR7TTaI=,tag:xfKWd6b3fN2y3IdIul5SIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKKzBSNTZBQWFtZk1WcFJU
            SmtidXhWeXVQRkh2VnlHcUFxKzRsbCtlRFZnClBJdTRuNjRUSy9YeE55U2xyTU5F
            L3dsODltOGxNY3dlcURTOUYxSm1LUDQKLS0tIE92aXZWWnFYOFcrSXkvRk44cExy
            NllPMEVIYS9qQjBiWmVVV3NnOGdURkkKewtfoT20T+KXMkSi8kwwHY17N7oLMxye
            K3IZkcUcwEI3yvJzoQJbh0EFVLYrwyHfiS7GaHpc0ws0QY+Sz2CjfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T17:02:36Z"
    mac: ENC[AES256_GCM,data:XsKILVuOcPLCzHsgeKufj8sXIDl3m0C+WhP5ITUmJ+vcyfcWpfpcdzpLU8G5qtnv+2wED2o177cSZhpah+ft6aqx1TQeDdblVGc4L0ZCCZCxd2lvJyLQ21sMO9iO/DUJo4phCjdQP9zrYKUmKSd4xB5bpIS48r7RZm2nzkmZsxo=,iv:sSO/yP82BqOt+XCGeFjWnmcX+1/rXugR/y9KBuNfNtU=,tag:2/gALbCN8C8pUJyHDwbpXw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
