ansible_become_pass: ENC[AES256_GCM,data:UTq5VZWR,iv:kzPNF9fm9Cl+OYX8lprdwbBPn9H+6kVNgUwBEcdpuVU=,tag:Vqna5MAbCbQtO5W1+sqtkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNWNTQ3J1Z0Z6UGlDVVVM
            UTdSQWJpSkg1OTNyTkxOL2hFd08rUElmVGxFCktJVVJWNjkzem1ydGxaeVZPREZ6
            OHBXS0gvNUVJbjJDNHREQ0x3VVcweWcKLS0tIC81dUpjOVpOSzEvTndvOGwxZDdB
            TFpPK0x5aCtQcFZPcklXTHl4blhhb0UK2oACEq9wwGJu48Z9ZQ1HlyDIzmhhIxho
            pojF+dnUMqunB/f1NZvTl15zLNg9JpUqOJcbu4bsIohTW/8QAUm4Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T15:54:36Z"
    mac: ENC[AES256_GCM,data:u71LmZmAgaAoZzeU5KzlAQBGo862RmRXQ5qJSVdYAzn1e15oDCsXbDUqoefZMevbXaZamZhghvznUAi2n2nAiovNKqEVZxKLjm1YLC4GrsI1vE6///GqwDu45zaev2j8yTT8qL2il45pqhY5KoddmbxF898ztnl+yptRf+Yv4Es=,iv:jJgwZdUp80qlaZz9ECXtKFn+VxY8YnHSkNcI9OqjBP0=,tag:wlFXn8QnXn8oHGE6RY6MDg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
