ansible_become_pass: ENC[AES256_GCM,data:S57KuI+X,iv:mAYPZFWqitTAjbc6qyndsPwFKXDqzysov3fQDZmDIwA=,tag:ofSwMIbDizhaxxfoWu58/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWEkwTVYySE8xSVZSeENn
            V3hjUHZjTU1NZ2ZEcUVTa1gydmYvM2FFMFZRCnJ1RGRiUERmVzIrYmx3RWhBUTVo
            VWhLZDhwbVZ4VXlvdGRYS2ttNG5IZ28KLS0tIG1yWG9kS1NqRHBrVWs3Wk5VQTZX
            dnAvYUZwYjJ6MG5iRHIrSXYzYXorYjQKBxdzhF6lyVJ2i/Wz6W7DdJvLAySHMjXH
            emycdDXqKE69q0zbn7BmG4Hcixf8gK2fBudPdwonEJbAStgWl4M7PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T21:23:52Z"
    mac: ENC[AES256_GCM,data:RoGMjEJ9B2ehcvcAay5Dv3kt7nnowfv3ehVZNovq4ckqopQ2C/AhGEGNM10hJ7g11AM9H5hBJ0Z1Kn6bPMefTQIExQEgd9pqcNFWvD2aykKNZExfMcXOC3RL3NKc9e79I4/RNuH5NTQ6tUXxYBL4JLOqx+qS2FQ/GeD2ww/iA9s=,iv:2lfQ5F4IZ/Ub4oGgUU27Ktpw9KAEw4jl4OtGd/sVnf4=,tag:AMlk0jP4WPkLROuGH3lz0Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
