ansible_become_pass: ENC[AES256_GCM,data:PRKX4Xty,iv:C4aejN3Q/t7M+5z41Fz6SRKeflhlBkc+g7X83eEo3OU=,tag:IaTlSeMq+WYvr6/AwgoELw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNzRSZU9UcXdQWDRIekhL
            WlloZzN0L09QUEJ1VFRUWTQxckR6dEFJNzFjCjZUQWFOWDNVSC9hMEJYL2JLQUNI
            VDBUa2JHTkR4NFNLNGR1dWJmTmdwdjgKLS0tIHlET055OFNZZktOeDM5OXFpOVJh
            eTJkZ2RiSURwTFFUR0oyWDc0cUpWQncKGPG7bHKSTFClq2TV3dkucGnSSNwepGSQ
            cKtmlV3ik8ilk3O5dC1PbHBkLYUeho8cC26PVtweW/XF2TVUIyNo+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T21:24:18Z"
    mac: ENC[AES256_GCM,data:9f6LRb9oZ8RaDZpEF73iB5kyrAg3vwlz4FeCmIFNgEQmVHyxqZoTm/5Cyo47Sb47v2igk/KbqgGOFrcvmpb2qsXIUFcVcMbv6u47nCkJxnmwEGyM+EoyQEWnafQMh2gFm90iLzzEXEobnTKaihJMgMfAMOnprDjOf/bBJHgn79s=,iv:N6qIM+pVIlJkqwMo4NnioJ7T8aUCz1Pc7x8kKKmSAq8=,tag:uYdImswHKwS7YwKrRefqJA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
