ansible_become_pass: ENC[AES256_GCM,data:Y0E9Lez1,iv:dkt3eoYn+MNXnymooHcmHuUd2Gt4O7vaPZOP8Nzdc94=,tag:bn5zKX6XQ0gvxt+9OBTD2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSmQwZk9kWGJuVllLRjBF
            a1daNENDb0N0Q1dLZU9UbHFicGgrWDlkMEFVCnBHWUJHUFZlMEJBckFzaC9QdmNG
            Um02dUlKQ2I5TG5YcTU0SElIQk1VL28KLS0tIGpDY0xnenU4bThFYzZIWlZ5YnlX
            TmgyTUZKZ3F3MllHZjNNdStKNStDcEkK/WGWMGRN34Rqnrdji45EqRHEa/CRWUui
            mpInmy+KIAlmGSmtJtfaDuaQIt87QboCiJBaAMNiQSO2fbBcIg9ltA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-04T08:28:03Z"
    mac: ENC[AES256_GCM,data:qJR2+e7/GAkhvdWKjpgAH917n1HBUuweIZm5A/wHccDZ6+P11WckdSo+tGDN8JYtfnhaaqOEgrSc2a52Cvu1ZbLKB4LcL9oqUGhj9IbmjGHJvZ5bCb5oIHlVJy4KDcylKtTCHICVK/6F3UYtG+2nC3OCoC5BeXCP1Mo9JGKaU8M=,iv:/pjnbGreFcOW0GLd/WzWJNwMF2BcI7/u7v5t5tTEjyE=,tag:Pn5DiBAnn+A/RcP4wA2ubw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
