ansible_become_pass: ENC[AES256_GCM,data:F2NxubfH,iv:TFtbtF1fosLdVq7phF/jJz5HOC9m+2wNE4V8iy3zlLc=,tag:TFNWBcO4j2XU50Th3pseYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSmpYRGN1MjBtNlkrTHN0
            VkZ0RjcyYUp1T2ZqMDNNU3VacGEzMGErUUEwCml2YjNFUUFsWXArVGgrYTRRRUpx
            eFZITjQ0bThHNi9HN1NrUlFWQ2J1OFkKLS0tIERJYnk4anJ3K3JsanE1S2pIbEVK
            VzRwRXRZYithWGtIN3A0RkVLbnRGOFUKBloeGxUlYrC+wZpZNJSf8TCgO+hVtKpk
            2m7lLS+meDsC/PoScJroZ8um2F0Xwib4B1cRpOsTUbro4WZkM72dPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T21:52:27Z"
    mac: ENC[AES256_GCM,data:RQY6H8F2SNvtL/i/Q9KXnZhVxVreYqRIb5oa2PZOMJuYkQYzo9vPZCg3DfxC39I2dGunuP5mUB2muAF6ZX/PYCnwW5JhhHVBIKJZHDxjc2uvKwcaQ2MC8L6Mow+OSjcNB3bXwI1NGISj6E4QwDl4DoZ15Jl6/on62ozqP5IzVV0=,iv:dbrumrKlhIMkGv0vH7be7t7W5HPGb0aAJLIzlAzymDA=,tag:yGVqSXPn+RygqlGspqFUvA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
