ansible_become_pass: ENC[AES256_GCM,data:hFBlZid6,iv:gp6vwolbOiuRt/t+XwXUks2+4nSoIeVKSJoz/gIbZM4=,tag:JWQcKd5xz63slRo5z8HfNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQTRrUGgrK21SRGtRbTZ1
            OSs2aS9jNzBVRklMTHo1TzhLS3lVVktNWG1NCjJKTnZFRkpnckNnUUdCRXNIMEhR
            YUU2R3FqR1FTZE82U3c2TE5lL1Ird0EKLS0tIFJsT284dysvRFdnMElCQU5ZUkhr
            OFk4WUZVdlQyMTA1L204UE8wU1BCRXMKgRj8qn0d4wvS7A9xH5R9oRRn/S3eo4A1
            JqK/igTenncHqcd07WwDbFuZm1xp2TP0AZ/Nfck5mplhGpexA6v0+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T21:14:48Z"
    mac: ENC[AES256_GCM,data:Vz8biC5wTZ/cWJOYG2B6rjxJGoHL9AJ0F465/aHLmG4akEHSErXCjF2zSnue/9+XTQBi9vs036B8qmK3u+8OVS9tQwAaSghSv2k2wfo99SK/+Um321Eui3j9BSXx/GFJZXUGBJoZ+2q6UN/E4fVNOVL2xHr9s6dFjDhmLff1eBA=,iv:8kU164Xazyj/WrfEGDumelyVZzGWTEmWjiWxC3qpmDw=,tag:AzY6pLWj31uUajy5SOM68Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
