ansible_become_pass: ENC[AES256_GCM,data:0IIPZAGT,iv:8+uqJUq84dSAyB/1TfOn3RnFME6nqzobZbyzENp+cLs=,tag:kZJtD9D0lI+lUwZuugUZqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYyttZjF6TURkM0MyUzR3
            eHQ2bkt4am5RbERaelEveEd6N01MU1dXVlRNCmlGcFh4L0F1R01GU21vdUFzcFpL
            MWZDcFc5aEJBV2l3KzJVdWJ1bk8zNGcKLS0tIHpPUDh0Q1J1c0JXbklaSHRsY1Jl
            OUhZMnpmTFJBOVBRcDRaRnQvNWszV2cKtGZvGefNRh9RwUiGWO3tW4gTn34he3jQ
            TXmj/EhnQP3t1APonhPBcqZgfs4qj23vfIpgIRVtMsIbc/aFeTZDmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-23T18:59:48Z"
    mac: ENC[AES256_GCM,data:4H1+EnjdKB6n+kqi+bz7UDhuuKiNNhtMquWdtSj/MgsyPmaeoqDb0zpMzDoyFEiwXQf0ft5njA9GtV+4VaR9RMhuDPt7JUQ4V5uGMg1ylPvBVKNacavCiMFmEQiqm0ekAk3Nfaq8OsuFTaqUWwhLM+dmQXPLLR3B860JWjYNvPE=,iv:/mEpkKsh1WKIP/yDVN3c940uhtA6igfI2WGd4C27MMk=,tag:5o4GUuwQNvwwUVVr72suaA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
