ansible_become_pass: ENC[AES256_GCM,data:0DCmGuZ5,iv:Kc0G2Nv1PFR9/k923oFypZByk95atZWtdWBzQs+jd08=,tag:2ZOepqEkV4JHA+p+TgyFGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZC9FTW9kcUNMcHFpdjEz
            ak1Zb0pvWENyU3pQdWNtdkF3T0dURGhCUHpVCitoZ0NPdmlWVE1JRzltcGlKTjhN
            TjZmbSswZ2ZCMVJab25rdDh3ZVBBWmcKLS0tIG5paU5Ca3lLT1JFR1BZTGJKdkRL
            bmlOZlVlTkFnY3NCNnUvQnppV3BibTgKUhGUHkEiuGSQM8jSvWYsfOc5AMdyWmoW
            0+LNONPzzY05RF9Fkd6nh1eUbQRBtmGGKo22VrZVpEbNo7buW5iJIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T21:09:48Z"
    mac: ENC[AES256_GCM,data:sq2Zz69QMjLnYDh/QUWQ9enLGUfuGRYTmnx8YyA8ZSgD/vf18z+SJHrl02fu96Bbf1PZteaVFDWVOe2SFo+3irgKlIDGv9yjIJwaMvyPZ/lgtFCGGd2emoZ7Ge1bCPP78pxt+SCpgb3hDL6hZVrtsN2hgIyHMQx0f6kjoSwsULA=,iv:jDxd1GaS2Qz1Pd1nDGyEhMKas3ft4rpLkdEh7F8Eob0=,tag:u0fcBGxOEGzIEcB4YUdGdA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
