ansible_become_pass: ENC[AES256_GCM,data:ysZU5/K4,iv:f0xIcNevjGA2ojg1SWVPd/UC5B3WcxC8LLxHh3Gd9s8=,tag:Fs721BhJYawmzfgC4kvimA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRkpKcXBxeEp1VEFpNTNj
            NU9FWG45YmcwK1I1R1FYOXMwRkNxUityWG5NClN4UGI5MGdTdVF3eGZCdXY2REM1
            ejRMUUxscXNoU3BsN0QvcmhQRXI2NFkKLS0tIC9FZmNyZE52dm1EWndyejk4TXYz
            V05OR3UzcC8reUUxQkhPRUdITlZuVTQKHaRKSBRy+f/j4uIk27FCcW4qOekuf/Am
            rKV4Ibwd4Tey2KZD28sczcIszV7vNbsmRrMOy9Z98OyAtxstGNsvyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T21:47:51Z"
    mac: ENC[AES256_GCM,data:E2zfgU0XHDyoq31wvrIac7YCAnLYtFB1uyXKj/XibT9JspltFaakRo5u5oPMHhIYzwWevGhb2yXj7OqvD9k5D7atHCTJFcKbEDTIy5/c9y48PR4xJtD3m+fbs2FZyaPoeGM8GMbBqkPzATbP45HwWJ4fiIaEUQm32DA5TX1Jad4=,iv:TG+abuOIUFZ48p2kfrsgKOHfMcyo2H+5wLsxdelWMec=,tag:XkGr3qobbSRuyPhDW4ZgCw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
