ansible_become_pass: ENC[AES256_GCM,data:PYi5EKKU,iv:LEShnf8oYd0NQGAddrKX8FWYs0MJyprwCj0pH/PfQHs=,tag:JkzN9n0aCUpwtzW183fCcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkV0RyZ2VsZVJEK2NhaHhZ
            MnZDQWpXRVRKK0VVYVBPeUlYTzZFbzdhNmhRCkE4Q2RFNXVkTW5FTHpjM05mYVkr
            MHpVNzJUZnR3ZXFyNmdhS2M1V29ZZ28KLS0tIDU0YVlBdExCczVoYWNkQnE3L2ZH
            UVFSQ243TW9pOUVCNWIrU0pvWlMvNjgKFgHv2eXX1EPzeCPeBv4lu2E1vpNAlur/
            7UkXIBg9tzt/5MTvK2lfuP9j5+JVP7DMOKm1LkZbssDDdrC0GAk42A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-25T19:31:43Z"
    mac: ENC[AES256_GCM,data:3aPmB6QLTdzXPlb41YZPlWc3cZwOtxvF1+ZhAJsuD9aKBYjvjwkeJmTqTcJvSF3arkUS7rV/qtgbM1HWpeHUAOveZHB3UfmJk4arr5AYmVthY5gZc2NWTFEICNUEvYEWB67MABnB2Nj1jD65XV16jgkJ3LWgul/oFCPL+2rvXsM=,iv:TSiqfTTQvfbY330YdlqQcHcnhDE3DCoGjBCyvLMVGTY=,tag:MOiU/zgCbB9zizKj6D1aTw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
