ansible_become_pass: ENC[AES256_GCM,data:VneOqPwj,iv:Ei8alIeKch5UPAqVZKdT+DN0ryXy1VGBnNoqCAtXH+k=,tag:orMJ5fxn3CldSLNTTtk9RA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZGppUHo1aG9mQ2JKRTVJ
            NmEvb3F0MHVLeHhnSlRTTmFlL2hldDZpaEJvCjNDclVjVXByL29mVyt2SUg2Wk9R
            VDdTL1JnbXNDdjJjS2lVV1ljSG8zaW8KLS0tIFRveHhGR29nelUvOGNiSDlWeEJl
            azFTb0JLQml4WklNVFUvOCt3WkM0bkEK1g170zCEp/otZJEzJrBLbO7HYJ4PWinB
            mJmDwcCJ0l/ZU0qIKzhKj4QY8wpTyeRPuXdDllN3f1CDT7Eh88HFBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T21:52:26Z"
    mac: ENC[AES256_GCM,data:h2viYQAgstfIBVuvI3d1B4+7Bz8vWouJo+jzuKyEmeosfoytvl80iCo7Du+LerkzRcbLhAAOrVZ9Tz9xLNdfJgbb9OBRK7RgiqC4EtF0gcnphMyTkF+aMZfLomj5lMrMyt4NvVpCPCKBH4W/55uA4JvsQv1TDCQ4K5ZFr8++xjI=,iv:6JyTniP07w72jOW3ETtyxCh2/G5gjtcyvG2DVp18AIA=,tag:LeAudtSl1svcveqfYV8N5g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
