ansible_become_pass: ENC[AES256_GCM,data:xVnaSn45,iv:fb8J0v7HjP8Rb2oMvOA7bKrT7nHSTzc+mUZUuM3H4lg=,tag:7E4e7PlMRW2PNERCe+p4AA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWFFocVdSeWFYR2ZxVldt
            S2ZZS2RnWEJBREpWbmZhUnhTNkd5V1BwcHlnCnVnOXVWVE13MFhSbURkb3QwUGk0
            SmtyRzM5M2QydjhjVGtwd3hLcWFpelkKLS0tICtucS96TU9URjRNMmdFZ0V6ZFl0
            K3J0dDZZSU1nWFNFRUFoTC9xNlhjbWMKx07U+UJGTEIm7EtD2srgWIAyqWSnNQOV
            lQDOe0DT1/TJIkjXmaiYLJnDpFVGEiiPRmBvudQz61wNHZfotS8Mvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T21:24:17Z"
    mac: ENC[AES256_GCM,data:qZriu0MpH3Madh010JRaDnPdLmkMVMVSsKQ1vfq1UMvSK1KPOgPSo5E39Hh2l4ka8NAdS2i9OoQnBQPSXNvksKtV8mCwxCoc830jsp/NO2T2cujX1GVwa1u35u/1rG4UOBfPi1WlJZbQDgl+9WayfVSfwe2Y03S9Qi9Rxj3GmW0=,iv:GHGATcA8k8W2x+YlRzFmq0k7a4JQlixFgzqfy77zeE8=,tag:H8s150Wk0QKjIL1fXkIfhg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
