ansible_become_pass: ENC[AES256_GCM,data:hFoMzzEG,iv:HyWaWUkGU9xg2twnZ9hFsMt4dc72i8MmC2Vf6/KtqFQ=,tag:kBO8Rme9xVl6mKeOtbQE5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QVFzcTBZZmJtb0pPVkRJ
            U05xY3I1azJ4enNObXhibEtUMHoxWVVLcW5BClp2OGo1RzFuSTdmZjRKQ1B5YjZ0
            UVRVd3NFaDJEaTQ3OG1TaGt2OGRXcXcKLS0tIGNYQkJudzgrb1FtSkZCcWdWZk96
            RlNrdTdIK3JpcEl5MjhKNHB4cXVjelEKHzl0Kd/l+GLKO8TjIXR6Hz2OFVAc5r6f
            JPcOMEspTSptv+LZ/CtbGznFeJgw3NJlrvJdbwD7Zq3D0tynJZ4dlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T21:14:47Z"
    mac: ENC[AES256_GCM,data:wjp0iT9MraReMh5mPEN1m2gDpSYJ4JGyUgYYQ1XYJ16gVpdrWYLnk8XWI/qMRD97hJnuPi0aHI886ZslOXAc4VD/9hxjigOcdRbWmggiWcEay+dQu/Bu2//9qBoXWl4924DmRePW4/gt5Po1n17zcyAbg+xA8xvmET8mWT3lVhM=,iv:Zk83/gkXfriWTkarDiV6SNNOlyLCP3tc7H2wq+WTTi8=,tag:gD9pbRE07/7fNHlJdSrxVg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
