ansible_become_pass: ENC[AES256_GCM,data:b8OBEN/k,iv:s0K8plqm8Bw3b73HgoDvdL4cf2ipAz7Q1Jw0WoImcbs=,tag:vpia8GZfsq2iBGI6KiSDwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTERkUXVpRDJKSWFtMVdO
            OUpRWjllZldHRkxpdjBoU1JRcXhWNXhkV0VJCnhNak9zMitJZ1pkcWpDU1BpN090
            dFlKOGUyaWI3T1pNT1p3NGpaZXVoa0UKLS0tIGc4WWIrbHZPWmFIZUliVCtheVhx
            Z2JIZ1NTNDJYZW5OZ0NMR3huNUxuNncKX972aKURf7eydpJijnbdxfEHNQuUTCFL
            PocRIn+eEu23YG9WKncUZVbk4LhnOhj6KcL7UQaDYweAn9cOcWVM+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T22:32:56Z"
    mac: ENC[AES256_GCM,data:Nu8Z96eCnxPrDK/B1SwBSgqkm3EjDcRODuWLnHREpvG2WoY2tcB0QQ9iyZ62Qu6cR4JwPQm4VXgUTYNVo/OeRMrDlBKZskgSM+Xo/itD8yuBGQ5HEtCCcMYWMJWCg2KQsC87mdy37NYuGR3gCdmxCrOJODknl1pxXy3Rz9XMBFc=,iv:0SnkeWLEhDqIuyMKfQeJ8r/AsJyh0pjMEqXUPYLHMdg=,tag:ZgF4wRdY9U/XFbYfSp8KdA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
