ansible_become_pass: ENC[AES256_GCM,data:1Zn1XlYN,iv:FdPtfzXM8Q5IXGcPkh7R3GtbjWZkZZfeETKUgHRwDlo=,tag:As0fk5Gh6c4xbcicFAKVVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdmxTb04zS0pDbUFBR3RS
            aUxoNVlMUWFqbVpaNm1zKzlSaklCa0Z0UTFzCklTVHFDTDZYYllaSVFzMzdhZTdB
            NVR6aURDOFRmM1hzSlNwZkd5YllFamMKLS0tIHc2SXJ6ODdrMlEzM0E2MHdNcGJh
            M2grYWl6eHFzdmk4VzVKSFRvRzIvRGsKfxcQ2E62w/82Fo6JRUT5wHEOfzaEmc8Q
            QEAzkuVgXXr8SRnbzQx+9V+09WVmZtbrRpV/YPmOxyCoCdXxtubjOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T07:55:25Z"
    mac: ENC[AES256_GCM,data:DrGS4sZcpisRgsxjLqeIDYJSg9BfKMTbeiNgRBFboE4T2ew4myXaG5iHn0cw1fh6Em1OsFN+z7kQ3UJyZhndUMbIMxAdaGi8ExSegav098Pj1ddGzug/E8YhHpRthfyf79ROzLerbjk7WDE9yPSXy6j8fZHIen6uKnN9UP+UiBo=,iv:XDlOOERytn3PUT23QSlJkb+dTvyr26jSXcpJYpIdZIk=,tag:rF7pfL6A6oQHlQpzY/iIaA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
