ansible_become_pass: ENC[AES256_GCM,data:MmLprbU5,iv:Whszp9DXZSasCfzv77jraCSOQ9zI9KvCXtcpWDv3Fk0=,tag:2WF3Y/ZVZ0Jvbz4eaJTN4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqemFIT1RFVTlXQUpYbU4v
            aDIzWGdDcnIwYXl4MUpOeERtYkpLcVFnM2xjCm9jSTZWY2hKTEg2OVlkbklGZFJV
            Z3ZoYlV4QnFFUjh4ZWtFT2o0UXZBMVUKLS0tIFJHLy9aOFhzVGI5V0doR0NYeVdQ
            QXZkRkFJZmN2WVdCbG4xVkhuVGM4TjgKNvRKcShShQgJG6UeBiigGpa7aZ0Y1HBD
            tDcB3jdPcrahCJM5SyxC1J2m6c8KXe1rlsy7AKY91OpZDLBSlaCQVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T22:12:06Z"
    mac: ENC[AES256_GCM,data:q9Fb4ui3X0dlCs+qwsk+mTWqgBUzcrgy+WNxqFFu7h1jjgD6ZS+X/adM4c5+uPaATy4nzBDG/jNw2BD9oeXwa5DE5eYH6Bao57WzeoKFFcboMy96JSIjTjn2WTMwKnEMxASrolJ/2GjZoz8rJ9qnakD0+l2V08j0Cj86bEMiKrs=,iv:AneBcNNisfOm/aMPzOIefEKt0O3EEw0qqCCQ9e5OmG4=,tag:KOxwGXkgHiWB0NwP9fCIEg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
