ansible_become_pass: ENC[AES256_GCM,data:EoHmIZ7Y,iv:bVo0Yk0gF1X5b3lHQNHcgYGKjng2ITQQZnLmiwjCm/E=,tag:scNJ01bT4F/lAs1UZlyHhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3V1ViSU1HWGRqMDhFazRT
            eHlNREdFQ3RUNDVXL2phb1hJc0FlN2ZmaENNCnVwOW9YckRucE9uU1FkR3hOT0pB
            NHpzcFlBVWZBclFqZ3lERmxLM3dOc2cKLS0tIHRiODZJMFZFWlM5NjRlb01kUUtT
            UUZTbVJ2U2dGNStzenRTOERHNFp0ODQKbwtlMEKOdzcxLRkHA+r9V+7iyMFR0X2C
            QDuB4HRsZJY58+mMOwOV22PzbyFiXQcXKd8olXNx149diSuYoua0IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-25T21:10:36Z"
    mac: ENC[AES256_GCM,data:6ffb9O11rFDa3h63Of+g9aR8OJur+L7pfgc70lcDbAb9fkkS8Bwe3jQfJTwx8PTBOSgnWcJ4wIeac8ADJw6ZFq3X7xreOV7Oi5RvZwAWiE6a/kli0uXe4w812F44D59vUSyIgHDqT6mIuvcqHaR8TUFg8/mJLlArs4VfXHcuh2g=,iv:NrTUPZpAAkA5V5l1nU334mZMGH7LlPpXQGfEPvxm9bI=,tag:g2haCPs6aHG74H1R4EauWg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
