ansible_become_pass: ENC[AES256_GCM,data:fGeT/KMb,iv:aSISCdnO3LP9dan0sKJoa3Z3zVtCdBYK8VD/W1gjst8=,tag:myk4ZaGBtDm3x4iQeZ0Y5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByL3BiYi9zengrSEhoL2lm
            TlpybjZBa1pDWFFEOTMxU0srdDVPWTB3bEVBCjFCZnllYkxOejE0VWpVYnJBWnBr
            S2xQWlNoWFY3b2VySFFyYkhWRmtFZTQKLS0tIGtIOVkrM0krQXlaSUxkSXAwTnNn
            NjVUK25uZEdYTzJZR3BaV09hbnpMd0EKdvijU2M8GqD2dlaMJ0VgeKGmOAz7wIdJ
            Tj5It7zl3UCRKiPJfGo9tG32ZRh19d1cqxPG8P45Qsj+RuvUoeVEow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T21:52:26Z"
    mac: ENC[AES256_GCM,data:q7ErovPeLQ1g+4sz/CZUjQCxTHuu4oVklAvxFPNR+xOzw8CHgP82RixBng2QAzgyPyR3elHtNO6yW8yyErBRFywBicrJ6pEfl7v35giCaIh94U6dkNvWw/WjnvNXaDPgKGAW5Y4TUkxcxO6FD2dMKWin1jRjg7GMpsq8zHfJ9sM=,iv:FHJxouOo1Nc1T+3EZ3V7WHaGWEdn2SctBFI64UJkKjs=,tag:FkzKhhoD0ZHajWZey12vcQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
