---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-server
provisioner: nfs.csi.k8s.io
parameters:
  server: nfs-server.default.svc.cluster.local
  share: /media
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
