apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:9vYcprj4,iv:b7Ix73DhsvOZcxo1rg9Ne+zPapRosVIXJbx6XEGWJ7s=,tag:pmkgIT5JZjGDeaGyTa/2ZQ==,type:str]
    admin-user: ENC[AES256_GCM,data:x99xnuY=,iv:nio67GSMPihLY+gAkSmehbuznVIXfrndszpl22UVSJk=,tag:WDe7fdtufg9nCxMc1+D9ZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVM0xMNFdSeVV0TitudHlo
            VTdJQWM5b29vbTBKWUxtYUxYZS82VTEzL0NzCkhBMkdnS1A4Q0pTNEQzMnVjTStp
            eFpFTkl0aUpsaE5DTjVOV29vdGlpdUEKLS0tIFJURzRxS1IrdHdxNlpPeERQcjdC
            ZURQTzdhUDhSd3RwYXl3eEw1VlpySkkKFgojDbpEqgSvm74ZsUJeXhPAHyIHxy3B
            gQKy0oCxOVpmdP1SpTBHA1JI/AVQmtWeWdm73Eq9MnlZRavJtHnfGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T21:25:29Z"
    mac: ENC[AES256_GCM,data:kcV5U3cwc3PfKHRpXze10HrSADWS8K6YsGb2S73vnMT1JGItgKuJWfEydPhbw//+C038VrIK0KLnIeIeouey4pv7h2t97BL/v2Yf2CByCoL6juXtLVLqPUGndeAqjn2SFPbejN6br2Ys+lbl268lJqwOy1QkTeHuKhYrU42QVFw=,iv:VYrKeTuvOUXX21ROLFyhelx/2r5GGfs7StIA43IfXSM=,tag:jsLO3IHQXUX1vrt8/VQOJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
