apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:/E+3OqYN,iv:RGRUdB2V56WGDdqcmtEN8L+1cxxaQivmgmxon0xrVnc=,tag:89RAOSpfPpItL+ME8QH2oA==,type:str]
    admin-user: ENC[AES256_GCM,data:5qzNAfA=,iv:Aw+ZrI+YrjO5/rqjfKPoEibXqwuc9yQzw5Ruq/82XDs=,tag:8Ecli3nF9J92nLln3LQOYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNTBwRmtHaWVrR3MwR1U1
            cTdsWExYdDdnVTJXNGJkdUVQdHRmR3BlTUVZCjI1TnpYaDVzV1RLelVjd21VcUla
            NDl5WjViY3gxUnU1K2xzb1B6YVdsYncKLS0tIDFlR1BmdGtCOFQxRXFXMEpPQTdE
            MDNZby9aVVJmK3lCQjlkYnRBVnY1OUUK4X9tMrsQwRxRBogEmF0prfoNL0Kaa/d9
            8emQ+AS7l5PiFZbY7HAYACrHbkGhzSbE+cm4bpQlZUos0sF2QRLgXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T12:51:10Z"
    mac: ENC[AES256_GCM,data:A/diJA7O8DydiUK2PpCzycmJYpv38S+MRvcqXdAptmw8f6Uv3FOAaZsonW98ww4Zw+AbvAUUHmxM3Wuofq8yk2EPV5MYysTfcSKt0W/DFRgQ976MizW9VxjfJKWGr+/S7UohGsXeO4ldfILHa0oiFhDQMphz/3QAJZh9d+VgkNU=,iv:/lfWGYUVn/GDlKx/6dgGCeH0EbjwXvBrxxSbWO6vPuE=,tag:P8ANE5rIK94XacQXwOH5uA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
