apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:gIrvRIrg,iv:UEml0jGJ7s+CSBTy2w3fDV3ovdgYQSFkN9VMoIAHMC0=,tag:E/f7/Eq0A1V3VECZ51j6Dw==,type:str]
    admin-user: ENC[AES256_GCM,data:ica5PG0=,iv:cEN6L53r0FiUIi+Bc1FlO379pGcVmbVsmsy7yaj93k4=,tag:gKTprOBm9KGUIwhhD8XeTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieDNyT09ES2VYNVJJM3V6
            ajM4UDZPT29CZ0dOM1B6T01SSS9XYzFhUm1vCkpiNk9hNVJiRUw5ZDJIaFV5TmNy
            SkJsNzdib0R6UDBvOXQ4a0RVcFdpTlUKLS0tIFJaNENyZWJzRU5XQUNRK29jUXdv
            WmNJNklqcjY1OXJWTkswbkVVZy9NWG8Kk6LVqVoyxJuuSTKWnlQGktYXfAR32ZxK
            69VpWWdYNbU9hf6vNxThtuRcG3n/cDf3A5EQcSz7o/6ZUSo8pHITIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-23T21:43:35Z"
    mac: ENC[AES256_GCM,data:CaOy5wbjvxaB3jRAjRoHEefLxx8NBibSaChHYOV+b5Oiyk6TvgzH0GK/TPf5XYmjZLYAJ0oHZ56FivaXiFkvjNqSS0qmByDZWJUcjo19JfYsw48BKWDWM0l5yQ1TkD5XGt/Ye5xR1QbBQimg9yZJG0i6LqFUBBvOKN+oYRTJTcs=,iv:bp9fH1nDQx045YnE+M+VJ2cH/BgT9HYOau7lJMoLOQw=,tag:/fSOV9uq6YMeFZI2YpS1+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
