apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:9sGAoaEa,iv:wDLJ6SP2Uc5whEvo6diKxChliC9cTCgn7yFzx2pr6lk=,tag:yg4OtdOANedAbU4Dg7aW7w==,type:str]
    admin-user: ENC[AES256_GCM,data:yvUpsMo=,iv:OTBN/hdIdkqRWLA54PLrc55niswPPTjpN5d9AJ4Ai+o=,tag:iz1oHnXkr+rz4xXfkyGYjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeXQ1U2xBWmJDMDhFSktK
            NGRCWTZ1RGlZeVl0b3cwZjlqZUFVamtWcEZzCm9SWHVFRzlEMFpqRVNoWWNtNlEv
            cDRIdy9xWFcyTElXL29JQ0JQUE1kUUUKLS0tIFpmQXdMTFVMZ282aDlwdWV2MnBV
            U1RITllybkJqQi9NK093bXZPclVBSnMKylHxpMan25ioNwwGjQXF8TdT7PO9znnA
            LY6NBZONsBNqK/rkEWtnH45rzWkeZrAvHK3cbk8DFnixj9E6pj8dlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-23T17:25:02Z"
    mac: ENC[AES256_GCM,data:pS+4a6cBbdBx2riG3vH00Iy2vOIOOrtKYjnkeLA5E1ZKnvOLILKSF/OYIgRAk6VMOow8oLxJyQL/zL7x5juTtHWfBJtt+RxvRMutvb7844blCQ39IXxwDv0L80L7iIhAWPAa5/oey3H+dIfWGEOR0DSTY+CTf7yZasMJpQTlmpA=,iv:bN1uPwds8IQ5l5dJdUmcDdVi8P3znZgx1REEwYi0Bm0=,tag:p/UtJ+pKOy8Q9CZveOBSgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
