apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:kx23zKq6FtQMp0T2WmSzxro98ttEhfGj,iv:oi2wPo+376Yb+J4+1sTgVCeyrW6H6pCfyGmerRxztTM=,tag:5xxeKYNUhzDmc1LaebefuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsb280bFdLczQvVHZzZDB5
            ZXNybk83MS9DUG9FR3pTV09LVWZlSmxqZVFrCkZpZHJFd3Y3VGVqdjN0cytESjl4
            dXhwM0E5elNOMUpKcWdGY1FQVGxiYjgKLS0tIE43S0tUNTgwVWNCZlpjTC9XeUJX
            OE1MSXF6dTRoL0dtYjF0a0cvZHdob0EKPVbk0XsJgy6FU6riJSog1MuBXnaNl55x
            GEYtyRI7kmhVtoS2ETDa5NpVyAhuBeJIFj1PxRdJ2F4yYKxvpmRxNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T17:31:47Z"
    mac: ENC[AES256_GCM,data:JrwZVePU64+NAU6clQS1NwHl88R7TVjhoFPzxC+Sr5x+ULbHDYVlzKEqXeAOl9nsoZbxIwNDA1jZI1/gP9GWpG0iV8dWIPBSnmOzWB75ate5d57Rf6j+6OuqE+BHAfmOxRP6t+dI71ytE7LU2ri4oObDWoWyMWqsh4zDWU3gWZ0=,iv:nKmBFx6J59zDXtAmzueOyLkC9hOjVTrD/eiIgzKbL2A=,tag:QLPRREC29yN0SM5k/r+NWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
