apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:S/4ab/8dkBEVKoSr7KIIm7kVWwGx898I,iv:JErBs/pggaxPXOhxtnRqaBpJAbMtt3P+j694lQg74DY=,tag:GiUJaC4dZhgndrPUgK93lg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RmNFcHJPUm9xQmRucHo1
            N0s5NkhERUhmdC8vZ0VHMzdzbHhVOWN3WEFRClQxeUJZTmhvazRLMFdGUkozZmo4
            R3piQS9TYXE4MWxlVmp5WVQ1Z2JXdE0KLS0tICtMSUpmMmhzMmxiTG45bVR0V20z
            dytaVUVRdXZodW81aVV3U0swTkY3Q1EKm+2utQkK0WrspLAALDzV59qKyUX5NL9p
            TL20qZlYAkQxPnKcJsAF8o0M5SMVQVJr/50FSYjQVwRdmT2t2LrOiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-23T17:15:00Z"
    mac: ENC[AES256_GCM,data:UUcs2fg6sGWGZlwi7I8UouMU9jR3YXDcm4b99EN0jkMLmaC/f4/aWbYmqUGzi2U4449SVZ7tGywibfOJNdIHFshlPa1RizU4n+gtEW5PXRaHhTKUJAcHge8s1zoGQyjwmFwQ7dzK3lF0rrDwjI1Sgj7AbPJiw+c6tRv24MDKkWo=,iv:oz+ISDdp7SEIm6ossWM9FAx0p/1R4F5Jsnu+VZPay2w=,tag:x/RicoyU+8CsCPmxta6eYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
