apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:HH0bMyLnoEyGefBDx7BazgTbl9VoNxPT,iv:A4PrMN+EIcX91aOG5jR3O+ExEOwZH0x82Yi86L6N9Ss=,tag:KkdgqUF9GtWlqdhEwAIyeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcHhEMlg5RWdnenJnaVp3
            Q1VORERSa3FKWG5GUXRlVXMrZk1WekdaaWs4Cnl0VWpqSnpXRWZlbDYyTnRBOHUv
            MEc1RTRoeGF2SVg5ZDBEUndCZExXVjAKLS0tIFJPckdIVGg0V0hHTC84bWV4cmR3
            MDdmOVBnQ09VZE1aaVFtcWpHMzBBY1UKUy702NKBMRJULIpNlg8O6uMOy3rCuIcu
            tklMeq/7gN0Sa6pVSS/SQLpOA0FXEgAWrW9NJHv2keVz/NF9X2kVXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-30T14:04:14Z"
    mac: ENC[AES256_GCM,data:we16W5LCY/NYWjP57EyN2UhSCU5VM6AIN9sE03F9CtXnT/2XLdz0SyAavkV9gffuc7K59CEP4bmfKdQO8nfSmR28KJwDtiDLc8d1GrXHr3O02SVZ+bV/Bf5cw6UXWEHkFRRodFQ8ScUv+2JY2ZMNOnNIhSykzAXzGjuinA7xdAw=,iv:uZzFDoQrHbQuDpoJLn1ieCutglc8YIegWO53RrnFhRM=,tag:3FQWSlKzB3LUDBrie72aQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
