apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:E2j7AgvSLPbVaMwlZpbsd/aoi4SfqJrR,iv:6PJ4o4kAwuOt4FIVM1HY/1g11h7pZwrJpvBcug46WHY=,tag:zEnXKmzDN2LIAUMIkbJIfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TkFnUGdWU2RZQlRKSVRG
            M2Y3RkZ5MThFT1dNNkw3NUFleEUycGx4ZEI4CmduZW5sZ2lWQzMxUUg3RVNIOTly
            RWFhckR4aTE5RWlNeVh1Uit3WmpVTDAKLS0tIEJhTnY5VkVYdUEwcXlHMjRjd1dX
            NzZjdVZCMmdqQVl3TEUwZTZ0cExIQWsKXEf9vbwLtEptzWELUzluRGzVJ2UIgO5w
            oP0wOSQwTfJZ6hpLyklmctByCmyBho+DF2tMLkL/n/a4rxgDzBVHbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T21:25:21Z"
    mac: ENC[AES256_GCM,data:3G3978cvtAfr6hZAmGXGUh9od+EV99Ym4btSJPELbq1fpqL0rmvCHvM5sUGwdyABeLcMKIkZUs0eu5u+uV0sGkQ8XMDLC3a0N1qZwfmlmI/sZ9Fn9ksiPy7Y1yCQq5e5rdDPYNGa0l5Ow59kzOTD6qgtQdtvKmuU4H3k91+cdIw=,iv:LVmKoMXMuI+pTSClC05PDspLF6Y/aTpKnduvss22Kcw=,tag:BPMmdpmqm34RBqnnepZxjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
