apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Ir6pDp6tbg5beJ5w74wiMBdme0MbX8t9,iv:2XCz+Ec280IBBXQ9U/BkpARYUQj+dcP7iHHaFifsl8Y=,tag:cJrDud/hqUPX4prwRXw7RQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbXJSQklYZG5aTEZSU29G
            MkY4ckdSdXdoeEx5VXQ5dnRQdTNjVUVyRW5zCnQ1VDFZRXJvYzRSbitjNzV2TzZ3
            czR3NTZQcmx3MkhCODhWb2ZnZ3R0MDQKLS0tIEhIdzdvbEp4Q2ZndzhwMGpyMG1J
            Wk9NM3c5VHE3YnJlZ01vakNsUE5NRUEKPn8u37gwDIO6NJcxU28eLF3TfvSNtuW+
            3yIa4bK3IvA9i02bAiRapgd1s3OrpobUTIJnOWDkORKXNnic+rjwyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T10:36:01Z"
    mac: ENC[AES256_GCM,data:klWyqSEfjqnAYAtrBY0VyhRV0DIf3zmSAeXAFTy4SxNRGspSgfFmXJjnp85ilTWr7Ktb516/uYWhwOcY47QHHVbr2pIav+7+mWYQAKsELQKB1nAVLATsfnMvyfyrE/lUqn+2CJpVUp0ugNkqrgwN6PWg2PmGobCJ88JqYgoLK9E=,iv:iqtcFTl2kUnKrJZowVnkIPpRjq+fJB/PSf7OL4DRtzU=,tag:kkQlBJHnN0T2LlxM2hQOXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
