apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:g2jgNwgsCq7w5b4mouDBnswYCkjMsBI2,iv:YA6n3jPTvQ1uIvpZcJP13uFAVmLMGFA5dJ62WJ3MwcA=,tag:LzPclSj07/XTeugc3xIRvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOE4wdW1ER1F1Y05Fbkha
            UFhWbWVkN3NOSU1YcHNETWpkTjJHNE0zTVE4ClhUQVk4bk9DNDFJSTYwdDg1RWx2
            Z1BqUklnL0k3WjVoTjdCd2ZCeWZpSVEKLS0tIC9JSmZKQTdpbXpRTnlWQ3dlb3FI
            RGp3bVFDVGxGREFGNjY5eS9NOU1kaE0KpgvcPV4lIvqDeg4uAT3HDWFdeTlU+Gdo
            VUwCN9KayBSuL7Zsiig9MXMrfFV7mjdErSZehmbb6t8XBi2nnxmi1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-29T16:11:34Z"
    mac: ENC[AES256_GCM,data:DM+5kAQON8aPSF/RJSjroVU/oAycQhR18tjFcdp6Ir//s19bGp1Kmm2553JmsgeHYEF1H8LxLd7uwVtEFPf7z8mU/FXdHSrcYMn2K+4wV2ANJ/cdpAQiv8C05lUODdfqfsaP91i2xhCubb60BQZG63NwBqDtnPMp9hYQ/m98WGQ=,iv:IAnsRiKCvP4lRtXoGn3PeFa+58q+wNtDAKVbnpxROHU=,tag:J6aAXpP84VsLTI1hyUffgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
