apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:lNBx5RDc+Mw0U1s27UnANxGsdP6z6DU6,iv:yI2KnQqXlttsdntEBQuxEOc8XONEn7cRFB82nV5FDlw=,tag:WqEM+cmyeQwIxhUW4EjVCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ejAwSTVaSzBBaVRTSHlK
            TEh5R0V4NlpnL29yc01xWkxoaC9SUnExdnl3CjNwNEE2bFdrUDJ0NTBCeWx3azI4
            Y3NkdXZhMGZqbmtCTmxnSlJyTnIzc0EKLS0tIEVZRUxjMmFTV2JVZldHS0QzZkpu
            SkdFbndBNkkyUHJFOVZGYmJVZEwvRWcK0zAxKphtmXmrt5FpI04JHfTjWXblItdM
            tvvWrD94njFC63F5VFildU2xvGHwDt5wC/CJ9V3bxxH9qdw9oWSqAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-23T18:03:53Z"
    mac: ENC[AES256_GCM,data:WjI09dqcI10j+V3eeg40zPb7cYBfDpgt+APxNEqZDDa2AiknlZTbaMuibJD+eHFbfAlzrlAsex5PkqBWWAwB1dPoyaod7r3Kk9lCBt+BelDpT58CZsrmVKLkfBijJyIXITufY4c16JwZR0wOXtOMdP1IYnRMsr1i1cJhquhjF0A=,iv:ns60pSzWeAp+Ns0vmVwoj8WWnmLgz7rS+Ruf8/82sag=,tag:TzZhyQQNufr4d6mYeKwWxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
