apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ZKgh8j76erk5xcdOIbS9BMhZMj76wpTa,iv:QBiLN/gH4fZJKFFHEdRJSyAjWOEv4rHd/Q7dVwcl2P0=,tag:GA1kTzJjpHX9ncwX4DEaeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLT29jK0RtRFh3TGJod0Fq
            RWpKSXlHVjBzV3BycDMvYnJWVHRzY3RNOGdZCkQwVWtXWGlHRk45Q2ZVejZhSVJZ
            QisvK1Y5Z0lzMDdsV09hZENKVk9aNGMKLS0tIGtrb01IbFdIZGRvRVNqVEp0NTcz
            ZjAydklmYVNmWEJaZ3NUVXRERnRPQkUKZyUVDZdNgQwOO+Ff7IUUFeUXVOaCbzET
            oQ0E7/N/uC/UW9FOKwVmM+zh1C6CHDzdWmhyruMpq6dMWdRndk3EVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-08T21:57:23Z"
    mac: ENC[AES256_GCM,data:NX8atv2nvHoBKhliEbaIK0xm7ScByDSk1jDBf6QPnPbXDLPzJuqoOyW8/JmPj/iR7crcdXA2/Mise9zjACEN+D4FAlfMkbqbCF/bHFbVyj8kLRTzThpQ9W+3lCPR3TRRaZFSPCwN1ZvTXx3rHojQ+DF+5T3wsa7VX6WrwHTNla8=,iv:qrsxA/f5UW6EEFXgsOnIpyKiZOQ4/mJpRUiJPbUB2d4=,tag:oEoiUx59MjO4owGIcBmKnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
