apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:NAtIRtYZf+N9FMbp5Cvp1KALEcXNTvtm,iv:6q0KOrxyZxAX/ZjdEJBYXaKzvNYbs0mZFz1rDEwqihE=,tag:bAU1ap2QPhsifRzrartW8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dG5wVVROaS9OenZiZE5n
            S0JUdXFYKzJsVzVneitoUzhGUm5jcVFBRVdJCkRldWltRzlKbC9xalZvSWJudmVn
            Wno3YnFJNWVqaW9kS0lWSDB0SXZBc3MKLS0tIGhOSHFEZHdDNHRuNU5EaXgyUEdv
            TStKK3JCTStUS1ljSFZQNkpFcDJDVjAK+wu7toqheYcrFKCxfhLzGLR7NHiAGHbP
            I2KSqk19eFkCvzNvKMJyc+hroHw44ogBrPWIE0Oj58Qu5kz2dDyCcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-25T18:57:29Z"
    mac: ENC[AES256_GCM,data:BZJS7+gJjpjXpvcqzKVcdv7FRmqfFr7l8B3B+3eXc0DiEBFRfnwBPR4ModC6nn5PA7l1TujhHjpJK0bvhhLKUfHkL8VplPhbWXxwSJAyE7R6pcj0Va0xTDfBXKy4AzuR8Qd4BOYPQFWf7+948qdgvkhGjLWtiVhEQrwfevI0igo=,iv:IDygqKb8Viy6sjXwAX8ChLXf10MYkg8Z+k/P3fwL2Rk=,tag:sXijoGSQiOXR2pvoWekgjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
