apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:/9NSyKetZTn/VlGsLP9lJv5LU6VfRXb8,iv:LIaMwagflhmdpYM7PrdnVZc/yQoSIofJ9D98CsdVRnU=,tag:eH5cJ9mdAlPWkVYtt9r73A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVDY3M2diL085ZWNHc1hC
            anVwNmxod2MzcEJYbzRMOVdwdVdrTUhjRDJzCmJJMVJRTkVYS2UxQ05CdTY5VEth
            NC82QzBCZzhyMkd1bTZYZkxlZksvYk0KLS0tIDFRNnBoTS9DR0VwUTNDdnJwMGVC
            TkRxWlF4cFpJVjdtZ1gzTTdCYlFSM2sKWQb0Jva5aR7YfMTrPzwduo6Aa5zqVUVT
            MTEmeQSL+ABOa45Rzf+NCfDqUKOQtu0Y3z462KoBCuDhq+sXwYQaQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-21T17:05:20Z"
    mac: ENC[AES256_GCM,data:ia3MW8tTlokaIYUGyQ3Swkt3lS/mWE2S7b7sxBCOkUplp+kLW0vyFC6B/vKjmYRAkygvrYAXiUmJeA6Mz+EPY8h3qM7aryLXPAEh6Ggt9BmtoUxFwqXH1jJ71Q4/QGI4Qp1z2U43xw3lMWd0M/Uu5HR+tmmL/cc3fFT2Lp868hQ=,iv:bSFoWS1/gP1sdPcwieqEAb9f+jS6OopmURUxBJTLH6k=,tag:pqYHUVZECTMAo9DF2rZweg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
