apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:eLYtxbZREMee+RFYoYp0TwLvu2lERqTD,iv:dHlOvH44uymxDvZSCurSieyktOWdoLbmGcqYb5sWRyQ=,tag:HkNVHk035O+dXoSAVkvGXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWHY4VXB6WkZaMXAvU21v
            emVsRTlTTVRoZXB2TnFoYllFRW9MOUpqVUMwCnkyMWdES1N6T0VRN05wQjdPZWFz
            MFdadXZsSFNQOG03R1RqeXYwekJCVFEKLS0tIC9IekoveVZpRHNpQjdUZnRNdnFu
            M2VxTTUwYjFOOEsyc01tSm1sN1BzYnMKQHcfFycL+hJAiSXbwYMc3hfQE0yK0/6l
            5F/2QLMq+kX9LrFgAP2yjD4goBnhIvoT4ICGdi9mMHIEMhjxMQyNlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-23T09:05:25Z"
    mac: ENC[AES256_GCM,data:FzzYW4sZS8+xpkAqZX1XJPuOCEecHDXrGfx9xzwXQwGGEpmDDcxXVRfha/XEDcJ2kw1I4OkokvaavwTBQ/CladjXJ8NdABoiVpPILU8ptzCfX1Np03LP3p9jTIcbsUE8zFaNzQ7jbvrp+FQ2iFmRpCDr++fdVpIQGP6VkbAqebk=,iv:xZTVeTRYI6W9qBFjIeT08CvD8iGjB9+kWpJdgEvzY/Q=,tag:WbrdcwOevRHWxCnV3ANPiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
