---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vpn-media
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: nfs-server.networking.svc.cluster.local/#media
    volumeAttributes:
      server: nfs-server.networking.svc.cluster.local
      share: /media

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: vpn
spec:
  accessModes: ["ReadWriteMany"]
  volumeName: pv-vpn-media
  resources:
    requests:
      storage: 1Mi # Size does not matter
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vpn-downloads
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: nfs-server.networking.svc.cluster.local/#downloads
    volumeAttributes:
      server: nfs-server.networking.svc.cluster.local
      share: /downloads

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: vpn
spec:
  accessModes: ["ReadWriteMany"]
  volumeName: pv-vpn-downloads
  resources:
    requests:
      storage: 1Mi # Size does not matter
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vpn-config
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: nfs-server.networking.svc.cluster.local/#config
    volumeAttributes:
      server: nfs-server.networking.svc.cluster.local
      share: /config

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: vpn
spec:
  accessModes: ["ReadWriteMany"]
  volumeName: pv-vpn-config
  resources:
    requests:
      storage: 1Mi # Size does not matter
