---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
    - ./intel_device_plugin/ks.yaml
      - ./node_feature_discovery/ks.yaml
    - ./reloader/ks.yaml