---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pia
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pia-secret
    template:
      engineVersion: v2
      data:
        OPENVPN_USER: "{{ .OPENVPN_USER }}"
        OPENVPN_PASSWORD: "{{ .OPENVPN_PASSWORD }}"

  dataFrom:
    - extract:
        key: pia
