apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pod-gateway
spec:
  interval: 5m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
  #See https://github.com/angelnu/helm-charts/blob/main/charts/apps/pod-gatewa/values.yaml
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.9.0
    webhook:
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        pullPolicy: Always
        tag: v3.7.0
    DNS: 192.168.242.1
    addons:
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: docker.io/qmcgaw/gluetun
            tag: latest@sha256:63220ec07e40bdf5fdbfe0a6d39d0468ee25c93bd2b31b0e12005cd230b44b8e
        env:
          - name: VPN_SERVICE_PROVIDER
            value: "private internet access"
          - name: VPN_TYPE
            value: openvpn
          - name: VPN_INTERFACE
            value: tun0
          - name: VPN_PORT_FORWARDING
            value: "on"
          - name: FIREWALL
            value: "off"
          - name: DOT
            value: "off"
          - name: LOG_LEVEL
            value: debug
        envFrom:
          - secretRef:
              name: pia-secret
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        # livenessProbe:
        #   exec:
        #     command:
        #       - sh
        #       - -c
        #       - if [ $(wget -q -O- https://www.privateinternetaccess.com/site-api/get-location-info) == 'Manchester' ]; then exit 0; else exit $?; fi
        #   initialDelaySeconds: 30
        #   periodSeconds: 60
        #   failureThreshold: 3

        networkPolicy:
          enabled: true
          egress:
            - to:
                - ipBlock:
                    cidr: 0.0.0.0/0
              ports:
                - port: 1197
                  protocol: UDP
                - port: 53
                  protocol: UDP
                - port: 53
                  protocol: TCP
            - to:
                # Allow traffic within K8S - change if your K8S cluster uses a different CIDR
                - ipBlock:
                    cidr: "10.52.0.0/15"
                - namespaceSelector: {}
    # -- settings to expose ports, usually through a VPN provider.
    # NOTE: if you change it you will need to manually restart the gateway POD
    publicPorts:
      - hostname: qbittorrent-0
        IP: 10
        ports:
          - type: tcp
            port: 21902
          - type: udp
            port: 21902
    routed_namespaces: ["vpn"]
    settings:
      VPN_INTERFACE: "tun0"
      VXLAN_ID: "43"
      VPN_TRAFFIC_PORT: "1197"
      VPN_LOCAL_CIDRS: "10.0.0.0/8 192.168.0.0/23 192.168.242.0/24"
      VPN_BLOCK_OTHER_TRAFFIC: false
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.0.0.0/8 192.168.0.0/23"
      VXLAN_IP_NETWORK: "192.168.242"