apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pod-gateway
spec:
  interval: 5m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
  #See https://github.com/angelnu/helm-charts/blob/main/charts/apps/pod-gatewa/values.yaml
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.9.0
    webhook:
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        pullPolicy: Always
        tag: v3.7.0
    DNS: 172.16.0.1
    addons:
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: docker.io/qmcgaw/gluetun
            tag: latest@sha256:fc0b03da1a10fedb8fbfed6ebb34960234e4bfe764b6f301cae6aa8291bccde0
        env:
          - name:  VPN_SERVICE_PROVIDER
            value: private internet access
          - name: SERVER_HOSTNAME
            value: uk-manchester.privacy.network
          - name: VPN_PORT_FORWARDING
            value: off
        envFrom:
          - secretRef:
              name: pia-secret
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        # livenessProbe:
        #   exec:
        #     command:
        #       - sh
        #       - -c
        #       - if [ $(wget -q -O- https://www.privateinternetaccess.com/site-api/get-location-info) == 'Manchester' ]; then exit 0; else exit $?; fi
        #   initialDelaySeconds: 30
        #   periodSeconds: 60
        #   failureThreshold: 3

        # networkPolicy:
        #   enabled: true
        #   ingress:
        #       - to:
        #         - ipBlock:
        #           cidr: 10.42.0.0/15
        #   egress:
        #     - to:
        #       - ipBlock:
        #           cidr: 0.0.0.0/0
        #       ports:
        #       # VPN traffic
        #         - port: &vpn_port 1197
        #           protocol: UDP
        #         - port: &vpn_port 1197
        #           protocol: TCP
        #     # Cluster
        #     - to:
        #         - ipBlock:
        #             cidr: 10.42.0.0/16
        #     - to:
        #         - ipBlock:
        #             cidr: 10.43.0.0/16
    # -- settings to expose ports, usually through a VPN provider.
    # NOTE: if you change it you will need to manually restart the gateway POD
    # publicPorts:
    #   - hostname: qbittorrent-0
    #     IP: 10
    #     ports:
    #       - type: tcp
    #         port: 52421
    #       - type: udp
    #         port: 52421
    routed_namespaces: ["vpn"]
    settings:
      VPN_INTERFACE: tun0
      VPN_TRAFFIC_PORT: "1197"
      VPN_LOCAL_CIDRS: "10.42.0.0/16 10.43.0.0/16"
      VPN_BLOCK_OTHER_TRAFFIC: false
      NOT_ROUTED_TO_GATEWAY_CIDRS: ""
      VXLAN_IP_NETWORK: "172.16.0"