apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pod-gateway
  labels:
    # Avoid variable substitution of shell variables bellow
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  interval: 5m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
  #See https://github.com/angelnu/helm-charts/blob/main/charts/apps/pod-gatewa/values.yaml
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      # I am using dev version for testing - others should be using latest
      tag: 1.10.0@sha256:d728eac85f750b37c96a0dafd038561ea4b8035857802be1128ea9b19c61e181
    webhook:
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        # Use dev version
        pullPolicy: Always
        tag: 3.10.0@sha256:a8ed630613de277244dfe203cd11d05905d7eeba8d8c41e399b02ee9a847b2f5
    DNS: 172.16.0.1
    addons:
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: docker.io/qmcgaw/gluetun
            tag: latest@sha256:fc0b03da1a10fedb8fbfed6ebb34960234e4bfe764b6f301cae6aa8291bccde0

        env:
          - name:  VPN_SERVICE_PROVIDER
            value: private internet access
          - name:  SERVER_REGIONS
            value: Netherlands
          - name: SERVER_NAME
            value: amsterdam429
          - name: VPN_PORT_FORWARDING
            value: off

        envFrom:
          - secretRef:
              name: pia-secret
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - if [ $(wget -q -O- https://ipinfo.io/country) == 'NL' ]; then exit 0; else exit $?; fi
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 3

        networkPolicy:
          enabled: true
          egress:
            - to:
              - ipBlock:
                  cidr: 0.0.0.0/0
              ports:
              # VPN traffic
              - port: &vpn_port 1197
                protocol: UDP
            # Cluster
            - to:
                - namespaceSelector: {}
    

    # -- settings to expose ports, usually through a VPN provider.
    # NOTE: if you change it you will need to manually restart the gateway POD
    publicPorts:
      - hostname: qbittorrent-0
        IP: 10
        ports:
        - type: tcp
          port: 52421
    routed_namespaces: ["vpn"]
    settings:
      VPN_INTERFACE: "tun0"
      VPN_TRAFFIC_PORT: "1197"
      VPN_LOCAL_CIDRS: "10.42.0.0/15 172.16.0.0/12 192.168.0.0/23"
      DNS_LOCAL_CIDRS: "local"
      VPN_BLOCK_OTHER_TRAFFIC: "true"
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.42.0.0/15 172.16.0.0/12 192.168.0.0/23"
      VXLAN_ID: "43"
      VXLAN_IP_NETWORK: "172.16.0"
      IPTABLES_NFT: "yes"