---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pod-gateway
  namespace: networking
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: pod-gateway
  policyTypes:
    - Egress
  egress:
    - to:
      - ipBlock:
        cidr: "0.0.0.0/0"
      ports:
        - protocol: UDP
          port: 52421
        
