apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:17U2dFYe1htBiuPhCRcIxQEHRKLmI6WTMEt/gDbTiYsUwLgEt66f0g==,iv:0BbIo8BdOm4f+qRsBcpdusq2DdHlKWrUDL7ZSMjkTKc=,tag:sT/zAcCTF0VbBCGFhZqToA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacmJ4cE9PV2tQSW8xa2Jn
            MFkzRXJCa1dQdW9RS2g0eGFNTEVMWFRtQkVrCkhwemdYSFZibCtLWFUrREFuZU91
            SDhpNlpkUU9vOExrdUtqMVZFNit0U2MKLS0tIEtpeTBMT3JKVjd6MncyclFvenh6
            NklLUnIxb2c2SDVLYU5MSXhqUGEvSUkKO208nU0oex/BwzbeN5ZmsUb2aIW4gwRS
            8n/et7Xu/50XIrUu0fy2nmoZ4kg+EIgKp2O/n/EzGdxCQYM1fo5/Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-23T17:24:57Z"
    mac: ENC[AES256_GCM,data:e+nzg9M1Zoiug3Up1IhvGly9oZ17ZDf4bUOphOWiatF2S8bcgVLUa/UFMCJeEHVkSi7TPR+Z2rW/AkgEuevL6uD65AM5tzy7wrp3R4LzjD1TdKAKrozkiVfGRbwgVOiC455s4l7gnd8Hc9rNQ72nn0aZ1rz0BSfitjvNfC1WTQ0=,iv:s5DaTurw/2xnOv1qBBQ8TNjrc3pSe+tcUms3yx77Hrg=,tag:x3VcxruanCvTi0/DWgjTgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
