apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:ISGHcgw5FWa9B8BzWgjnfYngVhX3ww1VC6Hqs1ud3EK+MdS5xUFtuQ==,iv:Rc9qRmRQ2R8ppNsQp533xwJj+qgKtQzCR1YIUjZ6NjI=,tag:GG6n4tpkihpXueoKC+JUWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodzJ2UFdZaExFblpnOFYw
            aTBTK3dHTVZ3U0VBaVZJSzBHU05RUld1ZUd3ClJTV1FtaHpIc05Xa2g4QmRLQmtI
            UGc3Wkh2dERFdkFWMXNTM1huWmdrWHMKLS0tIGFSZGErbkVrR3h2V29FSlJhR0hD
            aUxGb1JrVjVpVEVhVWtxZXNseTMvNDQKHgzkTbckPhqBHr6DwimYV5Q8AljirfVj
            PvVxEs5LcJ3Vpx84YMqJ2QJYBsEOwiV27W00SnYESA5hoK1eoisQ2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-01T11:36:04Z"
    mac: ENC[AES256_GCM,data:T9BU+665Z6Jn1M+DnMfn+8LsB7tp+6XAbClXfnf/stx4fh5DBMU7/vSZ+q4dzu7HgixgNQ2b3WZT1GINoCtctDmOjEGw3cgGblnyq5jk5KtEkI1cZ2q2Y+z+dbVMjKZLWcK4UVVP++lRpFcTeQpASQMQ2o1/1+4hCyFRtKBm6o0=,iv:6J8EFKF4R0TAUTTLtijrmUT1SNdEApx16SGxFdF/rxI=,tag:vSdVK/l5vi989h+v3swrsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
