apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:s3kSgHv4hou9e5MsCMbz7+PUGncjlRxjJfzTT8ZchE075gq2MA/2sQ==,iv:4diZuLhUADavvi/TQyp6rMWoA7oih6OaYTXxK7kgav8=,tag:3teTR42u4+rK8kVR8kNEjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZVg1TTJXeGNBY2toemRt
            bHdCcVJzTnJqR1N0QWlvVzFrWFJIVE14MkFnCkpMdGo4UUhEZWliZnQ5MXRxSkZU
            d3ZMYVYrUFhsRUxKZVlTeWN0VVVjZGcKLS0tIFBud3NVbC9manpoc3BSRzlmeWtw
            Z1hZSUxOcDZvemhicUZNY2dpR2M2OWcKls9d17Pvaop3zoW83rWAmSjSYzq01/hx
            RXy0koQfDSbfzALwEADbXNmXHKdUI8fj9cUEHvpJ0YG3rqr7qKYtMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-25T21:11:41Z"
    mac: ENC[AES256_GCM,data:F3er0pirK2uMgVdGi6mn7GpPiAeROkdAvVabtDTpRTlvP1o0cf6cc2SgsoMxsPqjFHvyhR7K2tYA3NpL7OQFpi1+p9x7Un7yqvyNW2EVzSi+ay12BVHQe0ukzb1WR3hF/vmV/nIb2ifqxfCZVbPRpikjZy9zA0yQYA2ZZ+tqSQ0=,iv:weKUwyK0000TywFkZeVdCVszCsedLQ+O3MkDW1pI2xE=,tag:Ezux3mprB3CoslHQ45ePYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
