apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:CqL4tDD5bZAX9ttsioWqZDyE01PdgvGpziOgmRE6l9N5rx2mfu+zRQ==,iv:tjo54LiVaPz0hvBt5S3xJUotwsShqK/209Gj3tCSVSc=,tag:n+f8HmVSZbcr6DwFFGwwCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaExBbmJpSXliLzRWOFBt
            R3hOaGIxYUhOa2pIRmJvcnhrdkNmSVUzczJJCnRxTTlvblptaXIzYXpIRktoNWpa
            OWw4Z2FFM1EwNmlyd1JHc0JQM251TmMKLS0tIHlqL1pBMDUrQjFrZzNUL3lRZkpw
            UCs1Sk04eWZEM0JodHhJVEFVQXhzdGsKQK88NuLl4lvy1DZqaL4y3BPu8n0Cva+x
            BjfKK+ZByjqEQOsATI7j/V0i5uJsGGsRnKkCI1FAMSysbNy8QIBCgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T22:00:28Z"
    mac: ENC[AES256_GCM,data:nRPmeqccYH85MOZihI1v/gXC1sKFTm6psAEHM+lq2OANj2+HVg9wstiHV4WVbqlxIUEhbOJoeXsU+5oOeF9e77k8jrQE6rHR5/48iSITOz0NOlAO1bmY9+V4/Z9aSLHdKQaS7O58qyl2JW6imWQ3X+L902SbehqZQiUJWAs0cms=,iv:aqR/DKo+Xbs2JbeewhUuCGZi99/uhY6oFD46RbNwFhA=,tag:MlqIMJ9mxtHCbG7dfVSTfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
