apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:ApCyUr2bH3LPpeeWobu9HqRxJnOPB2eqxwddu/Fv3kEuWhZdLXNYcg==,iv:Wyez83q7aqlrHayHPnSKimmgEAkIaMY1jPFA55yJ27E=,tag:DW+WOFUHHAQeq8Yn9wXDuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQ3JoMHR6Rm1vMXBuSVNw
            ZlpSQXpBKytQek9Sd0tqZWFzNVZUQ2hib0YwCnc5NW1UQVp6Qm9hak54UklzUzFa
            ajJrcndKMVhuNG9jWWdJdDRNZk1aQWsKLS0tIGg0cnBBa2xVb3d2WXg3ajlJQTR4
            eTJpUlRMV25PMy9nR2szM2J0NkVHdjgK3G4QYEkbNvW8Wnk6gVFR7w9jOWdQ6cHs
            lT79L6CnoUApgNwqI5GjZBiys3btqJFJzy9jxKYiCBQvuHiu6y2Etg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-01T13:31:26Z"
    mac: ENC[AES256_GCM,data:x8KOfpWTMnLfAau44aYqYHX4+guIXgxTkd+OCOT74IAXEkL9WzqtvRMlAeXHRLdpCKyYMIBGP8fcs2WhJ3GmNT/KrinU7UZP5ThiJmeG6UOBLeDB6ML9BFFVAiWmoXXDj+K1AotWjp14ToX5ZGsqVYB1uICeSFX/+xOgnyPWaoE=,iv:oLQvpjxslYSx/Nl8RfgQztN3oaPuzhfN8pGrCndeyAs=,tag:azTXQdqKhwwW5kVUhtrd0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
