apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:HZJgnYaont6f5L2FOkqe4RfjQDSFFab3X4p2X2xJqKFLmb02x5jZwA==,iv:L0w/ZkDMRwGmALGAgf2T/+nuEbzFQ4R9KtJs4XjYMS0=,tag:VMd6E8HPAGOLzTnaSt2UcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOFhFeXV4WGJBblFsWVBM
            U25CV1Q3aDNJNzlGN01vY0lZT09na0pVM3hVCm80bXBaaFd6SHhwbDJ6U29sampV
            UGNMemFIZkY3SytkMU1mbkdZL2d2VXMKLS0tIERPZmd3ckw3UW9QR3VEdTQzZDhQ
            cTBRVXdvU1dETVFCVk5QZHgwaUgwblEKvvvIuj3rloa4AZZv8an1mp8lpR/7Rc+e
            MZjxRPSJ0EhJgbrwSMQcp/JvLILHAQzlcbyB8wjNtwZ3lbdMNz9Wkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T21:48:51Z"
    mac: ENC[AES256_GCM,data:EJR3hx9yqb3VdqID0zy+DfYDG0j60zmSreYWPtKPYvMIWvuzFRJKLTFxF7+fkKJeRGWCbRcVCdCsYqEar+nsrU3wFx/ehU81zsPKjPXdpICCjkJvz5QDYqUZoB+1MZOAvWYaB/40fVp0wNJD5VZNjGbK08hiNIaY/VPmtcb798Y=,iv:JX/OvVu4/8UzIY21CYqxsNBTeE7WF/sbJ/a2JuySMB8=,tag:ZMYOqIE7h2Dhi8lApJ+zlA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
