apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:BsKm4TFVzx/dikb3gC68WW97vzJgQsgdJl6E5e7KYiWjG4ovaKyLZg==,iv:b7HAWsb6GP0A/z6s0F2Q6BBH8TasJn576aLt8i0QxP8=,tag:+vHGiExevuEl4UEYDoX7aw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWEtJRVVUdE05QnlRQkY2
            YW81clhIMUcvaWZ2YUVKVE54Yy82dC9OdVFVCksydnA4a2FhUUFrR1Z1S21WSnE5
            WWhhMmdUZTV4SkZNblFCeW9oT09MT1kKLS0tIG5rUWdSMlhKUFdmc3ovbjJydHpG
            bWN2OEZaclNOTENHNWRpUjVWRDJCWG8KmKiiNlGWEfhwkGy3ZGKsJYUK6ldub+GZ
            ayZc/jOBr59pUdmz491GnJ5m6Nj/BMDayXzF+VgNP5pP+9DCm5gqwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T21:24:55Z"
    mac: ENC[AES256_GCM,data:Dm0qVAca3/V3IVFM3v0wWMio12KGu394DgZx9EH8qlBXupFT09YDFU9G7XtghT4tsdMv2fNzpNJtCUELtS9Xlrf7Uk+c2+HY9Jt2w+4J5DNw/ChJ7q2QMBaugEXaM6cUKFDTNPINB0Yf/FPrZVbjEPnt3B2FVoeNA+injmb7Z5k=,iv:ENv38SGH8z/RA+/rnjKF9ymmXlDNI9iHQgBNKsxc2jQ=,tag:Qgsuw+vLQZ4wnJswJ+HB5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
