apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:uW/wbYAa0AKI+80gEEXiXevbygPhoJ3/mrQ/vVzNFuCUfRvzpsaEuQ==,iv:evWrEGlCy4chLmkeG3+PITDg2fsQuhlbOqoL/G9C8+8=,tag:kOVvOXwUZSQP4jT8a5iJFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWFBGeDQ0QnJuV0NRUDF0
            cS9BZGZVQXlwRUFZVWI3N1gvT0d2Z1Q4bkg0CkNrbm5UTjJVM3U5VTU2bFR3N09q
            dUJKdXBHdWI5VE03alpmdThoWlZtUkEKLS0tIGlSOWxKNjB4Y241L2ZLekF5ZzFP
            SFhaaDhyR2Z6SG1VYlNaQThoNkhVUGcK9mLOathLF9n3u+/997GcLxhuLA3I8T4C
            Sl/ZxmNkkb6lPULOc/J/U3IoT97+V4S1w/plhx4diGiMfR+2dwFu4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T07:56:28Z"
    mac: ENC[AES256_GCM,data:+G2rffUAc8isnhGw5Vxam6mTDs5rKt+kx2oTEOJxB4tFF0sDI+0r1h8nn5yIqW8UGrYX+lnnjmzqjOuFlvKi5Gp0EX3qb6eN1K+qowb7Wwue4awUDcxCv42XyGDW1flJwEYtb0u2LTtHB3dH7mugVqMJ6ZK+DLhiipd02E51Xnw=,iv:/Q1ltyxlSY90f5G0Km8dJsn51Z+kRKjtZAC5+Tyauyk=,tag:/3hvqTPcEEB0edbeBZJpzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
