apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:Zv7Qm2IFbbbe7IxMhYEN0VwGWHDPkRnJI6VhseN56G3SLhAp+wRoAw==,iv:Fj1eRC4b9bhoeP9cYacsnf+Kz43UCbrrlfIlkycKZo4=,tag:ZPmmqhrkC4VX1dz93hGPbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRWFNc1ZGdytuRWlrMEhH
            YnNiSmdYazI1Y3ltdzVuU0RESGlTZjdvbGs4CktuME52NTBjaFRmVzhiVnNjMHcr
            VC9scWc3N2wwRXpFSVFYd0NrVzJzVmcKLS0tIHNleElhZCtOWCtMR0xiNHhIYlRS
            UC9kSnAvd3JjYm4rVFBuZ1hGRkFuY1kK1hfq31jgCov3SErBNhOLYnzZ0DPtbCdH
            t7Vd/ohrQPaJLcLYe2gScoHBXv4Utfcv8nx5XqgYiAnTG2oS1smP9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T22:17:16Z"
    mac: ENC[AES256_GCM,data:HdAuYByqu6hhlh7R0hjWAsDVvQYnoF+QM71GoUPvZPZ98ay6/l/k1OB81RDI10jtjUnlCO1FlhNDfdLI+dvUxreLA0ZMfGBgAj2K6znuN1pgpOPR9i878gy0+YhL25lQOPXZrSeVLIXggqSktoVYe8XK9rEX3rKKOnIcudlk/hk=,iv:ribezYatH4eykecMxOBG+p/SytO6qrl8jr43t2k2iA8=,tag:auNWtz3IVptcbWhhkRr5FA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
