apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:rXm6/JB2z7UH0fGdwHJNS9GIt0/xLP+48R0E682oV3xV8nUpeSJm2A==,iv:juuI9EsbzBTta4Vp7tlTOHX1HzCGv+ggfatv7mLWMKQ=,tag:JqxktdeKj/R81eIf6ystbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVmFmYTVFZmxjbUpTQkVT
            R2pqQzdCLzQvV21iL3o1ZjFGcVAwd2J6UnhnCmtXU2t2OFFtSmxOcDAzcS96WXl5
            dkpJMnNkYnJla2FqcmJjMkhzNGRXa3MKLS0tIHE0VzFpSy9oQW9nbDZ6QXdYV2cx
            RUZJb1kvSUh0Vmk4NGlkUlVHOEpOc1kK+wUph1nF2MelQsnSFMrTJLfwUwJyc+xY
            sY8tqZqdjoOFasR0PuYVzBItRntrKH6u8wU5pFOGYOQ6DoIATmvc0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T21:15:51Z"
    mac: ENC[AES256_GCM,data:W5xb4SQXWYNGxkuWTlp5aJiWRia+Zz9brn0EeYWwsiohcpQGtjCV5KMkWOdNuXnawJGiY04lMs25qZ/G1l6UTYomV/EFrV52yatIllVM5qP0VzrF2UW7ITLvyE6HcB9lwVKHMpNPAPqlGlP3LogLsdKWjWDwuJCPL/eMt4YGiC0=,iv:yhYkw2zEieLl0F9OKvGEBDRY3SjPw5UL2CnSz/ZCVwk=,tag:wYlaoTBsymh7cc3SpLFHYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
