apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:lAAqdXqCE/FWbGmNNholmdkI9VhLwjpaRS0g6+9IGPyxAb266tbAew==,iv:RMUeCeFPMoJpVCRku03eHdUv3fQlENkUMrU462hiIbk=,tag:2YyzSmroNar5ysWoW0KyDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RU53SDIxVkdPaGZ3R0tM
            ejhYQUY0ekd3WUVKaXZjZlAvNFJUYmpUdENrCjVjVHhMVkl6OTBFZ1hidVJ2UWEx
            QWdST3Vkd3JpZVhBTE9pZ0N6NDFmRGMKLS0tIHB0OWZIRUJpZkxWdUx4M05hazdl
            T2c0Z2VHUzZib3ZHVEYvOWx0UVc4L28KppG3Gm2h/TqTBs8xY5dS864AsMxevWPw
            9KXQeWvICxTjVi6qOMmcd1Puyas0vq8c/MgqcMjIoJtx90lIKzn/zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T21:25:21Z"
    mac: ENC[AES256_GCM,data:yKk4e9hHNW+fj/wpENT9e4/imzRxlu8HiEnuKwWBZvxCNaFArDT+nRiCtRU6UNUsmxhA/MIslNZEIIH3vFhXlOJIJdTT6B11aeNZ0jl4KDehN9b1Og9xROhHMjilTX2Rkm3YKmpP7AnYURkQSy/6i4G/P5LzwGuKWPFK5+R2clc=,iv:86cj+AqUO/LUbPylmt6Nth8rsZ45CvGkZivBVFggU9E=,tag:shC/7nVyr+iMtOhduklPdQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
