apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:+llmPR2zmYLxAPSZiLBiRnAKHNj3z+TThwPq8Cb5yz1KCIb1rtxk4w==,iv:t0M7424Dl+KRukw6EDJXe86Df3VaCU6hlhIzJX849Lk=,tag:0foYP1FyUJFSqnhhHpPmug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVWl1Y1hqNVAvNXNUL0xq
            VmpWd29IYi9nUGtYUThYTWpub3Y4WkxoeVZJCldNOHJwcVJEcmQrY2dJR0lqKy9i
            cW5QQlp2QUFwTm1IMzJ6ZElwakZHRTQKLS0tIHNUODVId082Zm5vTmtvQUtOM1l4
            czlJSHJ5b3Z3djBHaGV2bkpETWpzRzAK3sGNffedIq9JSu1qYC/eVl5VkfMGN1H9
            0tmLIPVXpP3jilHkFJ/a/onL6R/kKplpNraG+3IfvnrL6kpHrnTtbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T21:40:20Z"
    mac: ENC[AES256_GCM,data:SrRwJjcVsI8KqSWxYYK3gzUhgDWPIbgCD2WLxrhAo0KAlzO5vVgDFSWnm5K4gHpPGFzYQV7bVn4OLuGQlGmo7RYMl+GMaObDHc0PyroEwlt0U7YQBDpT/x5LNm2pDJniPfnVtOhVBFdA4p58Rqhx1RyVZ6Lv2ftl0OH+jcA9FBs=,iv:+3fAYOBz3wzUHx9gZwyhpQbu/uq0Agl8+VnLZguCKvY=,tag:8kI9b9dhiY67LapUa6n1tQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
