apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:aZWINtLWQ7wqys7BTqxQAiHtNhyR+SiZ1/67C2tzu5ASaHaj7/EURw==,iv:rijOHrVcWZwlzq5JqfftW3BEqaUNF8Ov6BLLSzlUsh8=,tag:J+0adovQGUoAr4ov8jOFvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArT1lsQytBUlFveWxEa1or
            QWJvTUpBVnpuRzhGaWl4WGVYd3g2UkxDOVY4CkN3WnVZeSthOUJFSEI1QnBMdnFF
            dmwxZ1lidkx6SHU2Z0MxNkcxZ0VqalEKLS0tIGh6UnN3ZjE0dDZmd2tqejdJUmtM
            eHB3UjVGdkpGZmErS1loYXZTUSt4dXcK3JlpyOjvnmTyIQX9z+C/NB/uGgHCJvFd
            uoq91uwb4NE5P34wkIYPgWS7reXZG84s2usxEs4amfDMXkT7kaBkNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T17:03:54Z"
    mac: ENC[AES256_GCM,data:kg/lHT7YcmzvaA8ZSKRL/k9HIz0yXC99Ykjy4VwYRS9LnFuC94ePyIewhh0jQhm+xb2S8JLxPFYA1kqn1mRoN9oVBQo7fF4as5H7kDvFMJMPRHf6a9AJS9jnOdkNI+7GJ6r5/UPEHkLr6ZgrNAN1Utyt+s4etuiNebXRPPJ8428=,iv:OPns0cLdBEadaOjWfER6pHC/i2AWnAw61rV7mAO/vfA=,tag:mUSbDa+A+rx8RJC5kwkr+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
