apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:d2fMixyY5/6pGayv,iv:vOuD/U7yHWK07uL9HNsTDltLb3ShBp9oqaOqBn85SqI=,tag:JK4JEwDJvl3Zkf1XGB2hZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRWQycDdGQkNBK29yTVNh
            S0dsZDVZaU1tdjZaQ3JjblBFTG5Jb0RKcUR3CmRaRzlsMWdKenVtYmplMVFuNUdG
            KzYrblIvbVFuMXpZaGo0dm9FRWRYRmMKLS0tIHNDVG9YZ3lvQXBabFdQRWY0aWJ5
            TzBQUTRGdC9ELzhCdEZyRVR6NGJwN1kKcpJDPKXrQOAJGf3qppJS2ZJLMj/tCk9/
            AMSOp7KsyNIWFRn2/EaEU5ZXKwkFQ1rqagY1RcFov7yxICC/NWvO4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T12:51:04Z"
    mac: ENC[AES256_GCM,data:zKLwJX8Q4G22zpLdXp6a1nv6jtubNjP3AqirjlUlNWM/rLMTkBxAt7AyBbdsNfSiW5HyVTjxByIYtGq1ogdKlfaZBhktz1aKiD0nylcKPoyZdBZd4Qaz/9Xx8CTiD1K/8O/N6botmgUUx6lx+jS2vhpyhmm2XAb29sDMl8iLgv8=,iv:1H0P/jSrYiBD9e38WlzTmJ131uqh7dLb1ukXSgqWHnk=,tag:LmfRRKoE4EkAx797bI7+BA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
