apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:PKDccUQvivnS7UOz,iv:nz9VibwOnghyZhI5V1Gxh9+eZBB79cgk88kVycGC+9c=,tag:Uzdi/sPHCsomcH/IQYpI9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNamRiWUVPa1B4aEJyTVpm
            bWJwVjY1YkJaMkJ1UXRzTzNxNTF2cUJIUzBnCk5nTU54TlA5SUJId2Y4ZDdUQThJ
            clVmN1hGRVlSTnBFSDZ4M1luQlFwa1EKLS0tIGxPdHdUT0pyZG80VGJnQnp5YURs
            RFhTd1ZzMTUzS2YvSXZPVzkyZUNqZEEKZQ4Kuz4vqXau0ZefXghSIqYJXgn4yn5M
            m3ADmhbsTckcjd06/tcil3kFwvau6VtBoXIPJ/Ps68nokJf8LRT4og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T21:53:29Z"
    mac: ENC[AES256_GCM,data:072eynl682/anzhU1sx+F9jxPk61AAIARtUdjUCpL5bTcNBVKHNcST8jVzPqjjjJzqsjlZu6VjAdP8SzGSSrvVej+XypiXk6t89cFSFXitVfUo2VoQbspoMOaQQ0qrha9D1YWrqJ9PzEc02YbpxSSulyXBaA3LYHyLYDM62h81E=,iv:JSauxl+l0jFUdT6M+l5NsIy2V/xDIBxIKB/COyCPK0Y=,tag:IuAY05AFivBKkqXJcptBuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
