apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:q5O2pbv964uB/1R2,iv:HqFQ+uZSu2NjPJB3oA5Cb6ZhQ0S2jtczTWYZd5X62Y0=,tag:eugCjHzmPwjCxVau0TyS3g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:iO2nGC7rqNE/jvkppII2F2WdUh7xQ8EMuJFLOW/GoPtPph2A,iv:h4q2KGOL8ekMIOAVeNz1ZH04bbG+gHRNkDOCPd883Ic=,tag:VqCtC6pFgS0N0KJzFNDJ3g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:kJoVY1TGoA==,iv:eTKPIqA570wIIbvNz78/fjfy8l0McHQ7wCBKGkQP55Q=,tag:ZT3BN6Vgbe00cL0mJa1bqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWY0N6M0FyMzVmMUVWb1Fy
            eHVDWDU5cUd2c2h5T2x4M1IyZHpSWmRJUlFVCndEU1FNcnkxb2ZGbTBzS0pGeWV2
            bkI1R2JGWGp6S0ZiR082MWhubis1RXMKLS0tIDI4UkN3cFpYMlREWXBhMnlxZ0ho
            SzRuR29CKy9BUzJXazlveUdyZFNGM2MKus480Py+vpuPG15vLDw1Nn5vQlSRFIuo
            vRFnCEt6uX/z0bey7WV9ohrrjLkgcxEIf8c3vfNYAlzt02nSadFLqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-25T21:11:40Z"
    mac: ENC[AES256_GCM,data:MsEO1I53PY4kRv3Ao2BrEk9mbAqX3ZrKVvQfO4vmt3RK2SD9i9rkXXZlxcGEr8I/Sz53DFpR4LC2UAnH2fQ9ptHklz3EG41o04lXBVnTQt1DG05HSfGGWohBMC+xhjRESky0UiC+6VEMkE3qB+1RNpO2GvvojhDye0bcGxJb4GA=,iv:sYSUxipTsHHMdTO+WZ70WSHofwUQJBK4wecDuTOAvw8=,tag:hgAOFRnFBlo3yyLRY6Zadg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
