apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:QCF4381Z8/Wywy9H,iv:pYTUabz3Hw5PWTaoqTaZhcziQBP9NB9bFoV9199NpYE=,tag:dfvxc8yJDHkw7ttK2XX6iA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4b0VLMlRlWTdqSzRVSnF0
            RzVUdmM5bUZSaDdva2QvaWlIdVRNQVE2a1FRCk9qQ2Q5UVJUUFpLYTJzZyt0cjdB
            VitjWkg0aGVQOTkzbFBkeGpNM0FFZEEKLS0tIEdLRzgvcVZEclE3c2wxVEtiV2Jo
            TGpKRyttV1R6VzRmZlBPZnNaMU5UelUKzpf44YFsi/xPRaFQYHi2qDjnOFGBr1e3
            bJwff/u7OgCTKxg0PKo6bAU/lwOJm09qQ869qkD/JUtYUon0GbjOUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T07:56:27Z"
    mac: ENC[AES256_GCM,data:EFiODaXJrNRzv6+AeWjb7jfj4Pif9Ry6uMe88AkkvrqaRxqHR91joHIruHDidmp2CXDOazIG90rUFPi6yzRdwion807Q/51tZNrz8MG7X2jjYpCUUSqvFJe7Qj5JiC35i8fHeRqNm0O3LOJEqiCUDJJF9da2f6Ql1DZfthpE2QA=,iv:rC5/G6PzYoov8vDZVqXVuJLdVfRtU9vomzBHEUK4MQk=,tag:3JfTixnMkXjGpv8K6Cp1rQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
