apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:tHU/28zfHpv/yuJq,iv:3/Ir9dh+bNxRc3JIp2OCY131kw+PYzUYv1caOn4ea5g=,tag:SCrrrPxqO5BU6CJfK9098g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdi9RRUlBZDNLSTM5OEdZ
            WmJEOW1oUDg1UmJxOFZDNTFuSlByZkxQVFVVCm45VlFwL2QwUWdwc1h1aldUVnAr
            enhRZkNKNVh5ZjBPV002RVFDK0ZIQkkKLS0tIHpQVmY4RFlRL3pZOUI4eFM2VWt0
            ekdBTXhiUGI0YWdQamY3OFBLSCtHeU0KzP69dRFuFNc3ObTNMxd76SmuOvaBg7ua
            Gc0F//iVjdKC0R//KntxQdazjJb4EIP5j5XqeBWB6wAEncZeu9ixSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-23T21:43:27Z"
    mac: ENC[AES256_GCM,data:3ETGfH2pw4GPqzj1hOYT8k+aemEesdeOo4PoJjcMgOHmrPE1IQFOhvv00zlHEpQNzEirKWFGvG46f2XnVKQLWgnIGj8vEextJ4wlTUvnyLk+9pF6ZOLrBvtPuYoXoKkH4hGw/cAClrL8PcUadlodNsvJinU9pMe6QKt3tzDHLlk=,iv:tFLP2NYEwt95fxEKddT7/pQBnLuqvg46hBc1nbSLKpg=,tag:60IAillGYryASN2jP5/LNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
