apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:JLd/ypiKbzM7lh2T,iv:jHN33v/S1Z4kNk8EE32V2JXWbVyiq0iIw4lm3c//RX8=,tag:pPryLTqqrdeUWu+47C9zUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSlVXeFZoU053STRVSDdZ
            M3NUbHphRERUenFuSlFkK1dScHFQNUZheEV3CkxqOVZBZDFuaUQ2OVpqQVg4bXl4
            ODdqV3NkWUFjdDRZWVE2dTlFdnJrNkkKLS0tIE5IaVBQd2o0eWEyaHZqejdkZ0Nv
            L05nRXVXVDlVNy81QkZITHJQbmZtNDAK2zKSFolLzRsokS6Q4bbzv0wbsickKYRP
            fBB1mJy7BljjIer1iimEWdFRvAJY0K4AD0e1ucLDr6EyeFTatYLOhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-25T21:11:39Z"
    mac: ENC[AES256_GCM,data:ovZEID/u+dHuHfwaxsvwpZ3CAcHMfH1ebG8nCCR1JgKTOwfiJJF1HtF6EG8d4MfP2PvGZcpvJe6Ba2+qGVkeogZuhtujfxzUJ7W0/YLJMb7tXCeW7bPV99XiPYw108gFyMzUCUwqz6mskE7HlkLKw+mZt/5/1RgH0nVR4iG8KEE=,iv:tx+p58Gttc/hAeQle1iDcrQGt7w+7cEcybYTBrHcIJQ=,tag:zWuvdddtzSKwxdAs4BIT5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
