apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:VChQgGS3Pp8lcXIm,iv:KWV7MN4J9saAB9CMPtVlscamCxVVSqWXNlWWeQThzNY=,tag:tSGTFXuWykluuFwPQldiLQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:RrseEr5d5A3dkcptGI46YgoDt1h/9kd/CBn/ccuoF0oizLKI,iv:XZPff5FZ5WCVbEGEhHxsMaI1y3J20VQHroP/KRVwnzM=,tag:P3QVE4pBoDKBnOa8EzxBOQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:7BRXp7m5cA==,iv:5DAJ4vlVA7Px/ESoZi9BQK6CfF/u/tS5OQjVoIqy2Z4=,tag:nPwMIzRq7drw+x2T8bYedg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RTJKalhJMjJlZXVEVXdl
            RTdmK1Y1bW9mNGdia2FBdzJxK25KQVIzUUEwCmZoSFpFOFBMQm4zNGtzT2Z3VldF
            amVCSDMyREt1UFMrQUpSTUpZS2c4d2MKLS0tIDFVRjN0SndmUU9LTjc2cVNyQ0dE
            dWdlRXV2NEpubU5KWlUzWWdoZDZFSG8KuDU7Pkaf7H3V4dF6AkAN7PwllagCLAl6
            dqkZIVmfh5g/faAAsRJhpwpGzYV4D4lr3rA7+OnyXHpqB0M6zED78g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T17:03:53Z"
    mac: ENC[AES256_GCM,data:8VZCHM76Xrffbv0N3Os3orx2LUXKRf1CUYA39Y1n24fyVeu6HfqvJTWMFqb2epA6SJQ3QmPrbTE24Sh7qnUqLRziQm642c7MrY4nzsf08vOvb98cgPEu1eQbVac5VelR+vxPP/nfEqji3bJDpS+j5T3+/s2Dmg5tWnGnAGh/11o=,iv:TDOpQ6YoOc1qBKPMVDgy1p+xnvjF8/6UNKisCV2QL9Y=,tag:Mc33OtXfB0E40/ysrU8x/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
