apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:sQ3b64m/Sul5/PlrVACcXU0+AMa5qUT5L6a++qHA4Jr/6U3y,iv:ibG2a1ioebM+O0WYNLDj4DhXqj5l0QGlG5ImDjQ9nv0=,tag:LX8WAWoUVCuQVYRTLRVmkQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:KFcA1v0K8oFX+q+NGdMn/4aNVBYKnuaNyMwOPm21Xx0FuAL7LvMcwixiAJtwVgdCGMKRkLATyP2lxOA4+eDjJevxWrS+cGclqjQMudO2W8rCXSnnrOG0BwdoqAXG03JBCdL6OYEax5Wmt6Lam54CnVupeU6QIz4DC2wOLvVaCMX7fCc5S/H+h5Iqvyymawrn1g634Fad7XVTvbnA+dvt7gMuwnBfJ3zWdYHsHDpJ+w==,iv:ZI/iHXP80CkxH97oWoE4VZVL6imvkzkbGiD9IElMtqU=,tag:Rs6mdnX2CTGs++4COf1SVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Qmt0RmJQTzBKR2hhQ1Rz
            L0I5YXdiSlZWc1pqcmIrczVkMFJtQWNDZlMwCitLVnRUNVQvWVc0ckFXbDQwY0pk
            RDczMTJzZklBT0w2bEFVNjZmMm1GYVEKLS0tIFhHN1UyMmw0WjlwYVM4c3dxTG1K
            ZWhkNzBFZ1lzTTFpOVo1Slp6aTFPZm8Ky7ILN9jvitw23yEfJX3tH40Tj8ZqPPqw
            VYsIf944iWJBOUTMpzfLW++4H2F/3rpcWIFAyHRNdWbfjF5iIj32CQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-23T17:43:28Z"
    mac: ENC[AES256_GCM,data:lR8EfSEi+iFit/ZvO1MZdTcFjlfWJD/iJBbk5MXD7c2ABnPz9sKVJgkhvpdFyBPEmBZq3LSpGIkpd/yiuKtBlprZSfR8pRdJttKy6ludktqKpDGv1xWe4oFexZgIkXXQZPGzDlAAJnWZwIy/ylNID2gxbcRLR+x1fhZyDXb1ki0=,iv:jz7coNZdP1paYlje3wr5ylSyUznJOaidRbxtVvlloAk=,tag:ud6MET316rBeAu6i8Blixw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
