apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:1O71/H8d0GMXcJJzPPMJYlRbb3klvuBihq7O3Qy2wILMl/31,iv:8xqv7jNbI+o8Mo0htyR+jGsvwe9lIjv6DbcbmD+ZrJw=,tag:lOIk26Ghuo4yEMo1XcFpRQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:zRagbt8VMo5M6+L5IaEX6b8b0DasDQtIXXI8ijrBen16NZgOnsbJQuapItggidQV5mzxjPHa7Wf2zNWe6Etf3nB/zHFuBa9hqtsWZVs9MxIybDkaW8VhpLxxPtI275O/IA2qpxLb/ZvjvS8SYp7aryLwNjRe5rb9mMLrwZm1i8SuG6Gl/k4NSq6vbtIoM+K9BT+c0kB1Z4eXj3jCsCTuNeuITRmwf6ZjuK7UVaWzag==,iv:xK5Uxny0xlNi2NX7KiEOKg5gVsX/6fssvZ1tsewA8rM=,tag:kYdC6aTzUDAvpkjA1yxjlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeEcrNGRLSE5tSjREbTc5
            WFE4YUR5bTB6eGlLOHJTbFN4SlhnUHF5SUF3CjgwdUlJd0xzL05VTTFOZklHbzQ1
            UzR1anMrTDR3dUZmcGQvSFNLdTJFdWMKLS0tIFpSSFFxN0pBWmFyakR4RU9SV05N
            WEFXWCttQ0VDdkRQb0tvNEhGNCtsVDgKXZvm2JWvHIxSv94/pWHUThRZA8ynIYJi
            96CdECnovKY6XKwArzY9hPTJzO48vJ5mJiMs9iFg5yglIaTNhwBi4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-23T17:24:57Z"
    mac: ENC[AES256_GCM,data:gGu7kiFdOWYsUURCF1FifbnHVJfIIaZTSI58kpfwQVcWAybmLlq6Hl9V6Dd6R6x+H3OhAAMkgqMWhGz+AAhe67jXQHswz9z/moJmb6h8SFAUndHD5pHvGflclKY+JqyaIQMIoLu/9+FVMs7XS5obuxDal5iSnEuPdILDIgFYkNw=,iv:WO+AfLc2g4up3ntuALAJ8xIa5Ny/RoyHGBLy0+BKH28=,tag:NJn0iwmR6zpWJSVwrv4BPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
