apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:QSS43x7qsi747DFw3yCz5TvGqw7VCYMjzyb0Z8F7uSVnS2CC,iv:y3+TQIkC45pnPtAtjZytspkQI4I5HmAEmEWjf6bsnEc=,tag:mH5VtjifMuclBDRtTbRzNA==,type:str]
    credentials.json: ENC[AES256_GCM,data:KQTDZicqWUiDzOoHaZwP+IAVxgn8L/vcXAwnK0gqtKVxLcdBo5x8jk0Wo/q16dGGD2kDCLcuRaB0Wjz3uqOatjYXKh+vl+EbcFdrtQRTV/Dx9q6jhyO6ha7iDC7V8OB4L+LHmmxmNHAs0z4onIoqqoG5lhP+TuV98L8b6ltNnPkzL8KVCnooV0BVgdgnB4EzxUhutINRXcjUJUNbRI3C8jlQqf7yYUTf6yGRkf+hvw==,iv:OOWUm5uBYQWEc7+WsCzxvY3CRfN+orWxmJ1vrtZolLE=,tag:yEuQfSFio4GsiFQ/O9kRuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUW53c2xqdUgxZngvWDdI
            cENhY3Q5WS9HKzBQbDdMNkVhTXp3Q1phUzJVCmsxQzFJUENMSklHM1lDZ042clh3
            VHljZlMrbXA0RVh0N0pIVmYyT0VVSkkKLS0tIGQzYVk4SHZYM1BMTTMvVUpQZGFV
            cXZyUGZDb3hQU21LQ0ZuYTVGZS84U0kKIARtpyLDft7UdxAILL0PAIxMPUtY8tuf
            a3oavJCzoqZbG+OKg4wCPRXp7wg4+Jj847GfvEQVAB/tT3KfnROrJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-22T23:34:39Z"
    mac: ENC[AES256_GCM,data:ytJrIruZeAWUEIKeSKhmNxzWpf5alQ8FCHc4ka685HDZvMDm/5W4IjlnyJq9GTbDS129cjAganj9VqHLzQ8hrQc3b9Nef4FEKtBRxa5HasAWBRWLFtMBU/vKPKkHMlND+BcX24ujcOk4oIA0mzEKqmoP3+GZupC7vAkhKzfnEpA=,iv:0CqgfOBnWnUBryhnxT/fXoEAhO1XYwO5ntxrc1/UYrA=,tag:i2CufOUXIcA8M1OrBOpmeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
