apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:TjuebC7KZkfivDkkVadCvGdATa1KPDWjBbAhYDoatVS5bMQY,iv:UVJUlHOJ6ZOiWojMHcD4Kdp3tJs3gBvhqAsZeshKmdY=,tag:x9XoDbzciaXMbJBGm4rnig==,type:str]
    credentials.json: ENC[AES256_GCM,data:xYUj//jcMKwvhsgzL+2odRIzcoU9ySzTwnAwx4nBnNuZv7PgDxMTsKMyMm46XhZ1A1dmElI86w7IIUadzYwSR1/LWULGoNwt7pUTHeGSU3PQEiu/spB6/feraSxk2oh3ngGU33ZRaY4H8nKwYWNciNN8U+aJRslad8qr4aKt1VIZNx0AG/RW5+Bdg2FV04U9XBW33TJXn/o3fA3RIuKeP/xHniOYcUa5C++4cHgscQ==,iv:N0GnKAh/ZOUFKhhVTXzV0cAfEEbAVKUcW8gsyuZBwks=,tag:8CLbAZ+jitpQab3+yDrGCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s38mjx4w38k4ck0fmtg22u5x3nfuuygqds9egx4pt5mtzny7vpnsyf5wmg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkclFrOSt2Y2NvSzNNS0Qx
            T3kwcHRhS1M0WHFJZ1N5US9JYThKZWtKQTBZCkNUQ0ZmaXFuQUl3YWtWeDZMY0Nm
            cWRHYlNycHVFNWQxTU5yNy9MclllaFkKLS0tIDc3SkR5Z25vOXdyTTJ2UCtnWWoy
            MFJMdHRkYll4Ly9XYUNyZ0g5ZXdHQm8K2FDgbg0DTnVzQL02Uxm4s5kjqA3pt/6y
            gukR4yYlJx+njJ5Fxrzj0BDgTUrvf4TK6amEKlbCelONKcVevI9PkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T21:05:00Z"
    mac: ENC[AES256_GCM,data:8bA/QmQ2bbw+CTvs7ukBJr6e3ckyEolsjq6KATV+LK2q8c4l14zpSR3ouaTMPtnKaRPznUfy0cllZHv8B/RvJszalthegDLob4IR7FhGIfgKw2QxnErdajyGetHE839Wl+44CHYRSJAf+uPC657fg3LhqNZkDbwhxtHO3nE3Hw0=,iv:w+jENJJ8MEq7QFZuWLCJInDIiQ5Kl5/fzhSv5JPChuM=,tag:qqT1kcpRI0FdWbFcQ1gz1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
